Repository iced-rs/iced, pull requests merged in 2019-11, with the labels that each got.

#35 Scrollable widget
  core/src/widget.rs
  core/src/widget/scrollable.rs
  examples/scroll.rs
  examples/tour.rs
  native/Cargo.toml
  native/src/element.rs
  native/src/input/mouse.rs
  native/src/input/mouse/event.rs
  native/src/user_interface.rs
  native/src/widget.rs
  native/src/widget/button.rs
  native/src/widget/checkbox.rs
  native/src/widget/column.rs
  native/src/widget/radio.rs
  native/src/widget/row.rs
  native/src/widget/scrollable.rs
  native/src/widget/slider.rs
  src/winit.rs
  wgpu/Cargo.toml
  wgpu/src/image.rs
  wgpu/src/primitive.rs
  wgpu/src/quad.rs
  wgpu/src/renderer.rs
  wgpu/src/renderer/scrollable.rs
  wgpu/src/transformation.rs
  winit/Cargo.toml
  winit/src/application.rs
Labels: feature

#37 Text input widget
  core/src/vector.rs
  core/src/widget.rs
  core/src/widget/text_input.rs
  examples/todos.rs
  examples/tour.rs
  native/src/element.rs
  native/src/lib.rs
  native/src/mouse_cursor.rs
  native/src/widget.rs
  native/src/widget/button.rs
  native/src/widget/radio.rs
  native/src/widget/text_input.rs
  src/winit.rs
  wgpu/src/primitive.rs
  wgpu/src/renderer.rs
  wgpu/src/renderer/checkbox.rs
  wgpu/src/renderer/scrollable.rs
  wgpu/src/renderer/text.rs
  wgpu/src/renderer/text_input.rs
  winit/src/application.rs
  winit/src/conversion.rs
Labels: feature

#38 Debug view
  .github/workflows/integration.yml
  Cargo.toml
  examples/resources/Roboto-LICENSE
  examples/resources/Roboto-Regular.ttf
  examples/resources/ui.png
  native/src/renderer.rs
  native/src/renderer/windowed.rs
  src/lib.rs
  wgpu/Cargo.toml
  wgpu/src/font.rs
  wgpu/src/lib.rs
  wgpu/src/renderer.rs
  wgpu/src/renderer/target.rs
  wgpu/src/renderer/widget.rs
  wgpu/src/renderer/widget/button.rs
  wgpu/src/renderer/widget/checkbox.rs
  wgpu/src/renderer/widget/column.rs
  wgpu/src/renderer/widget/image.rs
  wgpu/src/renderer/widget/radio.rs
  wgpu/src/renderer/widget/row.rs
  wgpu/src/renderer/widget/scrollable.rs
  wgpu/src/renderer/widget/slider.rs
  wgpu/src/renderer/widget/text.rs
  wgpu/src/renderer/widget/text_input.rs
  winit/Cargo.toml
  winit/src/application.rs
  winit/src/debug/basic.rs
  winit/src/debug/null.rs
  winit/src/lib.rs
Labels: feature

#40 HiDPI support
  core/src/rectangle.rs
  native/src/renderer/windowed.rs
  wgpu/src/quad.rs
  wgpu/src/renderer.rs
  wgpu/src/renderer/target.rs
  wgpu/src/renderer/widget/checkbox.rs
  wgpu/src/renderer/widget/text.rs
  wgpu/src/shader/quad.frag
  wgpu/src/shader/quad.frag.spv
  wgpu/src/shader/quad.vert
  wgpu/src/shader/quad.vert.spv
  wgpu/src/transformation.rs
  winit/src/application.rs
Labels: feature

#43 Fix integer overflow with nested clip primitives
  wgpu/src/renderer.rs
Labels: bug

#44 Update `wgpu` to `0.4` in `iced_wgpu`
  wgpu/Cargo.toml
Labels: improvement

#45 Minor clean-up
  core/src/widget/text_input.rs
  examples/todos.rs
Labels: improvement

#47 Improve text rendering performance in some scenarios
  wgpu/src/renderer.rs
Labels: improvement

#49 Allow applications to control the window title
  examples/scroll.rs
  examples/todos.rs
  examples/tour.rs
  src/lib.rs
  winit/src/application.rs
Labels: feature

#52 Custom layout engine
  core/src/align.rs
  core/src/justify.rs
  core/src/length.rs
  core/src/lib.rs
  core/src/rectangle.rs
  core/src/widget.rs
  core/src/widget/button.rs
  core/src/widget/column.rs
  core/src/widget/container.rs
  core/src/widget/image.rs
  core/src/widget/row.rs
  core/src/widget/scrollable.rs
  examples/scroll.rs
  examples/todos.rs
  examples/tour.rs
  native/Cargo.toml
  native/src/element.rs
  native/src/layout.rs
  native/src/layout/DRUID_LICENSE
  native/src/layout/flex.rs
  native/src/layout/limits.rs
  native/src/layout/node.rs
  native/src/lib.rs
  native/src/node.rs
  native/src/renderer.rs
  native/src/size.rs
  native/src/style.rs
  native/src/user_interface.rs
  native/src/widget.rs
  native/src/widget/button.rs
  native/src/widget/checkbox.rs
  native/src/widget/column.rs
  native/src/widget/container.rs
  native/src/widget/image.rs
  native/src/widget/radio.rs
  native/src/widget/row.rs
  native/src/widget/scrollable.rs
  native/src/widget/slider.rs
  native/src/widget/text.rs
  native/src/widget/text_input.rs
  src/winit.rs
  web/src/lib.rs
  wgpu/Cargo.toml
  wgpu/src/renderer.rs
  wgpu/src/renderer/widget/button.rs
  wgpu/src/renderer/widget/checkbox.rs
  wgpu/src/renderer/widget/image.rs
  wgpu/src/renderer/widget/radio.rs
  wgpu/src/renderer/widget/scrollable.rs
  wgpu/src/renderer/widget/slider.rs
  wgpu/src/renderer/widget/text.rs
  wgpu/src/renderer/widget/text_input.rs
  winit/src/application.rs
Labels: feature, improvement

#54 Custom font support
  core/src/font.rs
  core/src/lib.rs
  core/src/widget/text.rs
  native/src/lib.rs
  src/winit.rs
  wgpu/src/lib.rs
  wgpu/src/primitive.rs
  wgpu/src/renderer.rs
  wgpu/src/renderer/widget/text.rs
  wgpu/src/renderer/widget/text_input.rs
  wgpu/src/text.rs
  wgpu/src/text/font.rs
Labels: feature

#55 Edit and delete todos
  core/src/widget/button.rs
  core/src/widget/text_input.rs
  examples/resources/icons.ttf
  examples/todos.rs
  examples/tour.rs
  native/src/widget/checkbox.rs
  native/src/widget/container.rs
  native/src/widget/text_input.rs
  wgpu/src/renderer/widget/button.rs
Labels: feature, improvement

#56 Draw checkmark icon and filter todos
  examples/todos.rs
  wgpu/src/renderer.rs
  wgpu/src/renderer/widget/checkbox.rs
  wgpu/src/text.rs
  wgpu/src/text/icons.ttf
Labels: feature, improvement

#60 Make `width` and `height` in `Widget` required methods
  native/src/element.rs
  native/src/widget.rs
  native/src/widget/button.rs
  native/src/widget/checkbox.rs
  native/src/widget/column.rs
  native/src/widget/container.rs
  native/src/widget/image.rs
  native/src/widget/radio.rs
  native/src/widget/row.rs
  native/src/widget/scrollable.rs
  native/src/widget/slider.rs
  native/src/widget/text.rs
  native/src/widget/text_input.rs
Labels: bug

#62 Async actions
  Cargo.toml
  core/Cargo.toml
  core/src/command.rs
  core/src/lib.rs
  core/src/widget/text_input.rs
  examples/scroll.rs
  examples/todos.rs
  examples/tour.rs
  native/Cargo.toml
  native/src/lib.rs
  src/lib.rs
  src/winit.rs
  winit/Cargo.toml
  winit/src/application.rs
Labels: feature

#64 Update repository documentation
  CONTRIBUTING.md
  Cargo.toml
  ECOSYSTEM.md
  README.md
  ROADMAP.md
  core/Cargo.toml
  core/README.md
  docs/crates_graph.dot
  docs/crates_graph.png
  docs/graphs/core.dot
  docs/graphs/core.png
  docs/graphs/ecosystem.dot
  docs/graphs/ecosystem.png
  docs/graphs/generate.sh
  docs/graphs/iced.dot
  docs/graphs/iced.png
  docs/graphs/native.dot
  docs/graphs/native.png
  docs/graphs/web.dot
  docs/graphs/web.png
  docs/graphs/wgpu.dot
  docs/graphs/wgpu.png
  docs/graphs/winit.dot
  docs/graphs/winit.png
  docs/images/todos_desktop.jpg
  examples/README.md
  examples/scroll.rs
  examples/tour.html
  examples/tour.rs
  native/Cargo.toml
  native/README.md
  native/src/user_interface.rs
  web/README.md
  wgpu/Cargo.toml
  wgpu/README.md
  winit/README.md
Labels: improvement

#67 Stop emitting private use characters on macOS
  winit/src/application.rs
Labels: bug

#66 Make `tour` work with `iced_web` again
  examples/tour.rs
  src/application.rs
  src/sandbox.rs
  web/Cargo.toml
  web/src/bus.rs
  web/src/element.rs
  web/src/lib.rs
  web/src/style.rs
  web/src/widget.rs
  web/src/widget/button.rs
  web/src/widget/checkbox.rs
  web/src/widget/column.rs
  web/src/widget/container.rs
  web/src/widget/image.rs
  web/src/widget/radio.rs
  web/src/widget/row.rs
  web/src/widget/scrollable.rs
  web/src/widget/slider.rs
  web/src/widget/text.rs
  web/src/widget/text_input.rs
Labels: feature, improvement

#68 Allow `Application` configuration with `Settings`
  examples/todos.rs
  examples/tour.rs
  src/application.rs
  src/lib.rs
  src/sandbox.rs
  src/settings.rs
  winit/src/application.rs
  winit/src/lib.rs
  winit/src/settings.rs
Labels: feature

#92 Add `From` impls for `Length`, `Point`, and `Size`
  core/src/length.rs
  core/src/point.rs
  native/src/size.rs
Labels: feature
