Repository iced-rs/iced, pull requests merged in 2019-12, with the labels that each got.

#74 Fallback to embedded font when system font is unsupported
  wgpu/Cargo.toml
  wgpu/fonts/Lato-Regular.ttf
  wgpu/fonts/OFL.txt
  wgpu/src/text.rs
  winit/src/debug/basic.rs
Labels: bug

#84 Process events only when necessary
  winit/src/application.rs
Labels: bug

#101 Added path to image hash so it updates when path changes
  native/src/widget/image.rs
Labels: bug

#99 Schedule render after `Command` futures finish in `iced_web`
  web/CHANGELOG.md
  web/src/lib.rs
Labels: bug

#94 Improve window setting
  src/settings.rs
  winit/Cargo.toml
  winit/src/application.rs
  winit/src/settings/mod.rs
  winit/src/settings/not_windows.rs
  winit/src/settings/windows.rs
Labels: feature

#95 Make scrolling behave like you'd expect it to
  native/src/renderer/null.rs
  native/src/widget/scrollable.rs
  wgpu/src/renderer/widget/scrollable.rs
Labels: improvement

#90 Load images from memory and image viewer example
  Cargo.toml
  core/CHANGELOG.md
  core/src/color.rs
  examples/pokedex.rs
  native/CHANGELOG.md
  native/src/widget/image.rs
  src/native.rs
  wgpu/src/image.rs
  wgpu/src/primitive.rs
  wgpu/src/renderer.rs
  wgpu/src/renderer/widget/image.rs
Labels: feature

#106 Use cfg and path attribute instead of cfg_attr for IntelliJ Rust support
  src/lib.rs
  winit/src/lib.rs
  winit/src/settings/mod.rs
Labels: improvement

#107 Implemented `From<Color` for `Background`
  core/src/background.rs
  core/src/color.rs
  examples/pokedex.rs
  examples/todos.rs
  examples/tour.rs
  wgpu/src/renderer/widget/slider.rs
Labels: feature, improvement

#108 Improve text input behavior
  native/CHANGELOG.md
  native/Cargo.toml
  native/src/input/keyboard.rs
  native/src/input/keyboard/event.rs
  native/src/input/keyboard/modifiers_state.rs
  native/src/renderer/null.rs
  native/src/widget/text_input.rs
  wgpu/src/renderer/widget/text_input.rs
  winit/src/application.rs
  winit/src/conversion.rs
Labels: feature, improvement

#113 Password input
  examples/tour.rs
  native/CHANGELOG.md
  native/src/widget/text_input.rs
Labels: feature

#121 Fix `winit` version to proper alpha release
  winit/Cargo.toml
Labels: bug

#111 Svg and icon support
  Cargo.toml
  examples/resources/tiger.svg
  examples/svg.rs
  native/src/widget.rs
  native/src/widget/svg.rs
  src/native.rs
  wgpu/Cargo.toml
  wgpu/src/image.rs
  wgpu/src/image/raster.rs
  wgpu/src/image/vector.rs
  wgpu/src/primitive.rs
  wgpu/src/renderer.rs
  wgpu/src/renderer/widget.rs
  wgpu/src/renderer/widget/svg.rs
  wgpu/src/text/font.rs
Labels: feature

#122 Event subscriptions
  Cargo.toml
  core/Cargo.toml
  core/src/command.rs
  core/src/lib.rs
  core/src/subscription.rs
  examples/events.rs
  examples/pokedex.rs
  examples/stopwatch.rs
  examples/todos.rs
  native/Cargo.toml
  native/src/lib.rs
  native/src/subscription.rs
  native/src/subscription/events.rs
  native/src/widget/checkbox.rs
  src/application.rs
  src/native.rs
  src/sandbox.rs
  winit/src/application.rs
  winit/src/lib.rs
  winit/src/subscription.rs
Labels: feature

#130 Resize text measure cache to avoid panic
  wgpu/src/text.rs
Labels: bug

#131 Fix `Subscription` missing in `iced_web`
  .github/workflows/test.yml
  src/application.rs
  web/Cargo.toml
  web/src/hasher.rs
  web/src/lib.rs
  web/src/subscription.rs
Labels: bug, improvement

#132 Clipboard access
  .travis.yml
  README.md
  native/src/clipboard.rs
  native/src/element.rs
  native/src/lib.rs
  native/src/user_interface.rs
  native/src/widget.rs
  native/src/widget/button.rs
  native/src/widget/checkbox.rs
  native/src/widget/column.rs
  native/src/widget/container.rs
  native/src/widget/radio.rs
  native/src/widget/row.rs
  native/src/widget/scrollable.rs
  native/src/widget/slider.rs
  native/src/widget/text_input.rs
  winit/Cargo.toml
  winit/src/application.rs
  winit/src/clipboard.rs
  winit/src/lib.rs
Labels: feature

#134 Avoid rasterizing SVG when a dimension is 0
  wgpu/src/image/vector.rs
Labels: bug

#137 Add `Length::FillPortion` variant
  core/src/length.rs
  native/src/layout/limits.rs
  web/src/style.rs
  web/src/widget/image.rs
Labels: feature

#138 `Space` widget
  examples/tour.rs
  native/src/mouse_cursor.rs
  native/src/widget.rs
  native/src/widget/space.rs
  src/native.rs
  web/src/widget.rs
  web/src/widget/space.rs
  wgpu/src/primitive.rs
  wgpu/src/renderer/widget.rs
  wgpu/src/renderer/widget/space.rs
Labels: feature
