Repository iced-rs/iced, pull requests merged in 2020-06, with the labels that each got.

#370 Improvement/58/feature gate font kit
  CHANGELOG.md
  Cargo.toml
  glow/Cargo.toml
  glow/src/text.rs
  wgpu/Cargo.toml
  wgpu/src/text.rs
Labels: feature

#371 Add custom window background/clear color (incl. transparency) support, fixes #272
  glow/src/settings.rs
  glow/src/window/compositor.rs
  src/application.rs
  src/settings.rs
  wgpu/src/settings.rs
  wgpu/src/window/compositor.rs
Labels: feature

#379 Introduce fill rule setting in `canvas`
  graphics/src/widget/canvas.rs
  graphics/src/widget/canvas/fill.rs
  graphics/src/widget/canvas/frame.rs
Labels: feature

#387 Add a comment of how to clear the display to `integration` example
  examples/integration/src/main.rs
  examples/integration/src/scene.rs
Labels: question

#396 Replace leftover docs in progress bar module
  glow/src/widget/progress_bar.rs
Labels: improvement

#390 Removed empty bind group from integration example
  examples/integration/src/scene.rs
Labels: improvement

#378 Add on_release message to Slider
  examples/integration/src/controls.rs
  native/src/widget/slider.rs
Labels: feature

#397 Intuitive `PaneGrid` resize
  examples/pane_grid/src/main.rs
  native/src/widget/pane_grid.rs
  native/src/widget/pane_grid/axis.rs
Labels: feature, improvement

#401 Calculated sweep_angle in call to lyon::geom::Arc was actually end_angle
  graphics/src/widget/canvas/path/builder.rs
Labels: bug

#381 Added `step` member to slider widgets
  examples/color_palette/src/main.rs
  examples/integration/src/controls.rs
  examples/tour/src/main.rs
  native/src/widget/slider.rs
  web/src/widget/slider.rs
Labels: feature

#406 Add `background_color` to `Application` and `Sandbox`
  glow/src/window/compositor.rs
  glutin/src/application.rs
  graphics/src/lib.rs
  graphics/src/window/compositor.rs
  graphics/src/window/gl_compositor.rs
  src/application.rs
  src/sandbox.rs
  style/src/lib.rs
  wgpu/src/lib.rs
  wgpu/src/window/compositor.rs
  winit/src/application.rs
Labels: feature

#407 Make `Slider` value type generic
  examples/color_palette/src/main.rs
  examples/progress_bar/src/main.rs
  examples/tour/src/main.rs
  glow/src/widget/slider.rs
  graphics/src/widget/slider.rs
  native/Cargo.toml
  native/src/widget/slider.rs
  web/Cargo.toml
  web/src/widget/slider.rs
  wgpu/src/widget/slider.rs
Labels: feature

#413 Make default text size configurable in `Settings`
  glow/src/backend.rs
  glow/src/settings.rs
  graphics/src/backend.rs
  graphics/src/widget/text.rs
  native/src/renderer/null.rs
  native/src/widget/checkbox.rs
  native/src/widget/radio.rs
  native/src/widget/text.rs
  src/application.rs
  src/settings.rs
  wgpu/src/backend.rs
  wgpu/src/settings.rs
Labels: feature

#415 Add `scale_factor` to `Application` and `Sandbox`
  glutin/src/application.rs
  src/application.rs
  src/sandbox.rs
  winit/src/application.rs
Labels: feature

#421 Recreate uniforms `BindGroup` when necessary
  wgpu/src/triangle.rs
Labels: bug

#424 Add `min_size` and `max_size` to `window::Settings`
  src/settings.rs
  src/window/settings.rs
  winit/src/settings.rs
Labels: feature
