Repository iced-rs/iced, pull requests merged in 2020-10, with the labels that each got.

#542 update to winit 0.23 api
  core/src/keyboard/key_code.rs
  glutin/Cargo.toml
  winit/Cargo.toml
  winit/src/conversion.rs
  winit/src/settings.rs
Labels: feature

#558 Adds From<Point> and From<Size> for [f32; 2]
  core/src/point.rs
  core/src/size.rs
Labels: feature

#563 Fix typo in `Row`'s and `Column`'s `hash_layout`
  native/src/widget/column.rs
  native/src/widget/row.rs
Labels: bug

#568 Require `Clone` for `Message` early when needed
  examples/color_palette/src/main.rs
  examples/tour/src/main.rs
  native/src/widget/button.rs
  native/src/widget/radio.rs
  native/src/widget/slider.rs
  native/src/widget/text_input.rs
Labels: improvement

#569 Remove `executor::Null` from the root public API
  src/application.rs
  src/executor.rs
  src/sandbox.rs
Labels: improvement

#545 Remove outdated `Fill` comment for `Column` and `Row`
  native/src/widget/column.rs
  native/src/widget/row.rs
Labels: improvement

#575 Custom Scrollbar Width
  Cargo.toml
  examples/README.md
  examples/scrollable/Cargo.toml
  examples/scrollable/README.md
  examples/scrollable/screenshot.png
  examples/scrollable/src/main.rs
  examples/scrollable/src/style.rs
  graphics/src/widget/scrollable.rs
  native/src/renderer/null.rs
  native/src/widget/scrollable.rs
Labels: feature

#584 Viewport aware drawing
  examples/custom_widget/src/main.rs
  examples/geometry/src/main.rs
  graphics/src/overlay/menu.rs
  graphics/src/renderer.rs
  graphics/src/widget/button.rs
  graphics/src/widget/canvas.rs
  graphics/src/widget/column.rs
  graphics/src/widget/container.rs
  graphics/src/widget/pane_grid.rs
  graphics/src/widget/row.rs
  native/src/element.rs
  native/src/layout/debugger.rs
  native/src/overlay/menu.rs
  native/src/renderer/null.rs
  native/src/user_interface.rs
  native/src/widget.rs
  native/src/widget/button.rs
  native/src/widget/checkbox.rs
  native/src/widget/column.rs
  native/src/widget/container.rs
  native/src/widget/image.rs
  native/src/widget/pane_grid.rs
  native/src/widget/pick_list.rs
  native/src/widget/progress_bar.rs
  native/src/widget/radio.rs
  native/src/widget/row.rs
  native/src/widget/rule.rs
  native/src/widget/scrollable.rs
  native/src/widget/slider.rs
  native/src/widget/space.rs
  native/src/widget/svg.rs
  native/src/widget/text.rs
  native/src/widget/text_input.rs
Labels: improvement

#533 Fix: ignoring all `target` directories
  .gitignore
Labels: question

#583 Add conversion functions to Size and Vector
  core/src/size.rs
  core/src/vector.rs
Labels: improvement

#586 Accept a function pointer in `Subscription::map`
  futures/src/subscription.rs
Labels: bug
