Repository iced-rs/iced, pull requests merged in 2020-04, with the labels that each got.

#252 Update and improve documentation
  ECOSYSTEM.md
  core/CHANGELOG.md
  core/src/point.rs
  core/src/size.rs
  futures/src/command.rs
  futures/src/executor.rs
  futures/src/subscription.rs
  futures/src/subscription/tracker.rs
  native/CHANGELOG.md
  native/src/lib.rs
  native/src/user_interface.rs
  native/src/widget.rs
  native/src/widget/pane_grid.rs
  native/src/widget/text_input.rs
  src/application.rs
  src/executor.rs
  src/lib.rs
  src/sandbox.rs
  src/settings.rs
  src/widget.rs
  web/CHANGELOG.md
  web/README.md
  web/src/lib.rs
  wgpu/CHANGELOG.md
  wgpu/README.md
  wgpu/src/lib.rs
  wgpu/src/widget/canvas.rs
  wgpu/src/widget/canvas/layer/cache.rs
  wgpu/src/widget/canvas/path.rs
  wgpu/src/widget/pane_grid.rs
  winit/CHANGELOG.md
  winit/Cargo.toml
  winit/src/application.rs
  winit/src/conversion.rs
Labels: improvement

#253 Release `0.1` - Custom styling, event subscriptions, additional widgets, new examples, and more!
  CHANGELOG.md
  Cargo.toml
  README.md
  core/Cargo.toml
  core/README.md
  futures/Cargo.toml
  native/Cargo.toml
  native/README.md
  style/Cargo.toml
  web/Cargo.toml
  web/README.md
  wgpu/Cargo.toml
  wgpu/README.md
  winit/Cargo.toml
  winit/README.md
Labels: feature, improvement

#259 reference feature flags in docs
  Cargo.toml
  futures/Cargo.toml
  futures/src/executor/async_std.rs
  futures/src/executor/thread_pool.rs
  futures/src/executor/tokio.rs
  futures/src/lib.rs
  src/lib.rs
  src/widget.rs
  wgpu/Cargo.toml
  wgpu/src/lib.rs
  wgpu/src/widget.rs
  wgpu/src/widget/canvas/frame.rs
Labels: improvement

#266 add init method for settings with flags
  src/settings.rs
Labels: feature

#268 implement ctrl + del on text-input
  native/src/widget/text_input.rs
Labels: improvement

#267 impl default for canvas cache
  examples/clock/src/main.rs
  examples/solar_system/src/main.rs
  wgpu/src/widget/canvas/layer/cache.rs
Labels: feature

#278 Stop generating empty `Mesh2D` in `canvas::Frame`
  wgpu/src/widget/canvas/frame.rs
Labels: bug

#279 Fix `text_input::Renderer` implementation in `iced_wgpu`
  wgpu/src/renderer/widget/text_input.rs
Labels: bug

#281 Align text in `iced_wgpu` on a case-by-case basis
  core/src/rectangle.rs
  examples/bezier_tool/src/main.rs
  wgpu/src/renderer.rs
  wgpu/src/renderer/widget/checkbox.rs
  wgpu/src/renderer/widget/text.rs
  wgpu/src/renderer/widget/text_input.rs
Labels: bug

#289 Produce and handle `CursorEntered` and `CursorLeft`
  native/src/user_interface.rs
  winit/src/conversion.rs
Labels: bug

#290 Remove unnecessary 'static lifetimes on `Renderer` traits
  native/src/widget/button.rs
  native/src/widget/checkbox.rs
  native/src/widget/column.rs
  native/src/widget/container.rs
  native/src/widget/image.rs
  native/src/widget/pane_grid.rs
  native/src/widget/progress_bar.rs
  native/src/widget/radio.rs
  native/src/widget/row.rs
  native/src/widget/scrollable.rs
  native/src/widget/slider.rs
  native/src/widget/text_input.rs
Labels: feature, improvement

#294 Fix tour example
  .github/workflows/test.yml
  web/src/widget/checkbox.rs
  web/src/widget/radio.rs
Labels: bug, improvement

#293 Improve `Canvas` ergonomics
  examples/clock/src/main.rs
  examples/solar_system/src/main.rs
  wgpu/src/widget/canvas/fill.rs
  wgpu/src/widget/canvas/frame.rs
  wgpu/src/widget/canvas/path.rs
  wgpu/src/widget/canvas/path/builder.rs
  wgpu/src/widget/canvas/text.rs
Labels: feature, improvement

#269 Update `wgpu` to `0.5` in `iced_wgpu`
  examples/integration/src/main.rs
  examples/integration/src/scene.rs
  wgpu/Cargo.toml
  wgpu/src/image.rs
  wgpu/src/image/atlas.rs
  wgpu/src/image/vector.rs
  wgpu/src/quad.rs
  wgpu/src/transformation.rs
  wgpu/src/triangle.rs
  wgpu/src/triangle/msaa.rs
  wgpu/src/widget/canvas/frame.rs
  wgpu/src/window/backend.rs
  wgpu/src/window/swap_chain.rs
Labels: feature, improvement

#305 Implement and expose `Element::on_event`
  native/src/element.rs
Labels: feature

#318 Make `Font` an associated type of `text::Renderer`
  core/src/font.rs
  native/src/element.rs
  native/src/renderer/null.rs
  native/src/widget/checkbox.rs
  native/src/widget/radio.rs
  native/src/widget/text.rs
  src/widget.rs
  wgpu/src/renderer/widget/text.rs
  wgpu/src/widget.rs
  wgpu/src/widget/text.rs
Labels: feature

#322 #321 Fix async examples by feature-gating Command implementations + A…
  .github/workflows/test.yml
  futures/src/command.rs
Labels: bug
