Repository iced-rs/iced, pull requests merged in 2020-08, with the labels that each got.

#482 Upgrade glam to 0.9 & use glam's Mat4 ortho rh gl.
  glow/Cargo.toml
  graphics/Cargo.toml
  graphics/src/transformation.rs
  wgpu/Cargo.toml
Labels: improvement

#484 Add 'transparent' in window setting
  src/window/settings.rs
  winit/src/settings.rs
Labels: feature

#487 Implement `From<Color>` for `Option<Background>`
  core/src/background.rs
  examples/styling/src/main.rs
Labels: improvement

#496 Fix cursor position after a `CursorLeft` event
  winit/src/application.rs
  winit/src/conversion.rs
Labels: bug

#500 Update `wgpu` to `0.6` in `iced_wgpu`
  examples/integration/src/main.rs
  examples/integration/src/scene.rs
  wgpu/Cargo.toml
  wgpu/src/backend.rs
  wgpu/src/image.rs
  wgpu/src/image/atlas.rs
  wgpu/src/lib.rs
  wgpu/src/quad.rs
  wgpu/src/text.rs
  wgpu/src/triangle.rs
  wgpu/src/triangle/msaa.rs
  wgpu/src/window/compositor.rs
Labels: bug, improvement
