Repository iced-rs/iced, pull requests merged in 2020-02, with the labels that each got.

#178 Expose `iced_winit::Clipboard`
  winit/src/clipboard.rs
  winit/src/lib.rs
Labels: feature

#177 Event subscriptions and custom executors for `iced_web`
  .gitignore
  futures/src/runtime.rs
  futures/src/subscription/tracker.rs
  src/application.rs
  web/src/bus.rs
  web/src/lib.rs
  web/src/widget/button.rs
  web/src/widget/checkbox.rs
  web/src/widget/radio.rs
  web/src/widget/slider.rs
  web/src/widget/text_input.rs
  winit/src/proxy.rs
Labels: feature

#180 Custom styling for `iced_web`
  Cargo.toml
  examples/pokedex/Cargo.toml
  examples/pokedex/src/main.rs
  examples/styling/src/main.rs
  examples/todos/Cargo.toml
  examples/todos/src/main.rs
  examples/tour/Cargo.toml
  examples/tour/src/main.rs
  futures/Cargo.toml
  futures/src/command.rs
  futures/src/command/native.rs
  futures/src/command/web.rs
  futures/src/executor.rs
  futures/src/executor/null.rs
  futures/src/executor/wasm_bindgen.rs
  futures/src/runtime.rs
  native/src/widget/image.rs
  native/src/widget/text_input.rs
  src/executor.rs
  web/Cargo.toml
  web/src/css.rs
  web/src/element.rs
  web/src/lib.rs
  web/src/widget.rs
  web/src/widget/button.rs
  web/src/widget/checkbox.rs
  web/src/widget/column.rs
  web/src/widget/container.rs
  web/src/widget/image.rs
  web/src/widget/progress_bar.rs
  web/src/widget/radio.rs
  web/src/widget/row.rs
  web/src/widget/scrollable.rs
  web/src/widget/slider.rs
  web/src/widget/space.rs
  web/src/widget/text.rs
  web/src/widget/text_input.rs
Labels: feature

#183 Integration with existing `wgpu` projects
  Cargo.toml
  examples/README.md
  examples/integration/Cargo.toml
  examples/integration/src/controls.rs
  examples/integration/src/main.rs
  examples/integration/src/scene.rs
  examples/integration/src/shader/frag.spv
  examples/integration/src/shader/vert.spv
  native/src/user_interface.rs
  native/src/window.rs
  native/src/window/backend.rs
  native/src/window/renderer.rs
  src/application.rs
  wgpu/src/lib.rs
  wgpu/src/renderer.rs
  wgpu/src/renderer/target.rs
  wgpu/src/target.rs
  wgpu/src/viewport.rs
  wgpu/src/window.rs
  wgpu/src/window/backend.rs
  wgpu/src/window/swap_chain.rs
  winit/src/application.rs
  winit/src/conversion.rs
  winit/src/debug/null.rs
  winit/src/lib.rs
Labels: feature

#185 Make `Element::hash_layout` public.
  native/src/element.rs
Labels: feature

#186 Container support for Align::End
  native/src/widget/container.rs
Labels: feature

#187 Add `Node::move_to` and make `Node::align` public
  native/src/layout/flex.rs
  native/src/layout/node.rs
  native/src/widget/button.rs
  native/src/widget/text_input.rs
Labels: feature

#192 Customize Checkbox
  native/src/renderer/null.rs
  native/src/widget/checkbox.rs
  native/src/widget/radio.rs
  native/src/widget/text.rs
  wgpu/src/renderer/widget/checkbox.rs
  wgpu/src/renderer/widget/text.rs
Labels: feature

#195 Quit application when `Cmd+Q` is pressed on macOS
  winit/src/application.rs
Labels: bug, improvement

#193 Canvas widget for 2D graphics
  Cargo.toml
  core/src/color.rs
  core/src/lib.rs
  core/src/point.rs
  core/src/size.rs
  examples/bezier_tool/src/main.rs
  examples/clock/Cargo.toml
  examples/clock/src/main.rs
  examples/geometry/src/main.rs
  examples/solar_system/Cargo.toml
  examples/solar_system/src/main.rs
  native/src/lib.rs
  src/application.rs
  src/lib.rs
  src/settings.rs
  web/src/lib.rs
  wgpu/Cargo.toml
  wgpu/src/lib.rs
  wgpu/src/primitive.rs
  wgpu/src/renderer.rs
  wgpu/src/settings.rs
  wgpu/src/shader/blit.frag
  wgpu/src/shader/blit.frag.spv
  wgpu/src/shader/blit.vert
  wgpu/src/shader/blit.vert.spv
  wgpu/src/shader/image.vert
  wgpu/src/shader/triangle.vert
  wgpu/src/shader/triangle.vert.spv
  wgpu/src/triangle.rs
  wgpu/src/triangle/msaa.rs
  wgpu/src/widget.rs
  wgpu/src/widget/canvas.rs
  wgpu/src/widget/canvas/drawable.rs
  wgpu/src/widget/canvas/fill.rs
  wgpu/src/widget/canvas/frame.rs
  wgpu/src/widget/canvas/layer.rs
  wgpu/src/widget/canvas/layer/cache.rs
  wgpu/src/widget/canvas/path.rs
  wgpu/src/widget/canvas/path/arc.rs
  wgpu/src/widget/canvas/path/builder.rs
  wgpu/src/widget/canvas/stroke.rs
  wgpu/src/window/backend.rs
Labels: feature

#198 Create `README` files for all the examples
  examples/README.md
  examples/bezier_tool/README.md
  examples/clock/README.md
  examples/counter/README.md
  examples/custom_widget/README.md
  examples/events/README.md
  examples/geometry/README.md
  examples/integration/README.md
  examples/progress_bar/README.md
  examples/solar_system/README.md
  examples/stopwatch/README.md
  examples/svg/README.md
Labels: improvement

#201 Fix `Clip` primitive intersection in `iced_wgpu`
  core/src/rectangle.rs
  wgpu/src/renderer.rs
Labels: bug

#205 Make output format of `iced_wgpu` configurable
  examples/integration/src/main.rs
  src/application.rs
  wgpu/src/image.rs
  wgpu/src/quad.rs
  wgpu/src/renderer.rs
  wgpu/src/settings.rs
  wgpu/src/text.rs
  wgpu/src/triangle.rs
  wgpu/src/triangle/msaa.rs
  wgpu/src/window/backend.rs
  wgpu/src/window/swap_chain.rs
Labels: feature

#154 Texture atlas
  examples/svg/Cargo.toml
  examples/svg/src/main.rs
  native/src/widget/image.rs
  wgpu/Cargo.toml
  wgpu/src/image.rs
  wgpu/src/image/atlas.rs
  wgpu/src/image/atlas/allocation.rs
  wgpu/src/image/atlas/allocator.rs
  wgpu/src/image/atlas/entry.rs
  wgpu/src/image/atlas/layer.rs
  wgpu/src/image/raster.rs
  wgpu/src/image/vector.rs
  wgpu/src/lib.rs
  wgpu/src/renderer.rs
  wgpu/src/shader/image.frag
  wgpu/src/shader/image.frag.spv
  wgpu/src/shader/image.vert
  wgpu/src/shader/image.vert.spv
Labels: improvement
