Repository iced-rs/iced, pull requests merged in 2020-07, with the labels that each got.

#292 add some accessibility features to web widgets
  web/src/widget/checkbox.rs
  web/src/widget/image.rs
  web/src/widget/radio.rs
Labels: feature

#285 Add support for setting window icon
  src/settings.rs
  src/window.rs
  src/window/icon.rs
  src/window/settings.rs
  winit/src/settings.rs
Labels: feature

#430 Add `ModifiersChanged` to `keyboard::Event`
  core/src/keyboard/event.rs
  native/src/widget/pane_grid.rs
  winit/src/conversion.rs
Labels: feature

#431 Splits iterator for `PaneGrid` and minor improvements
  native/src/widget/pane_grid.rs
  native/src/widget/pane_grid/node.rs
  native/src/widget/pane_grid/state.rs
Labels: feature

#432 Update `dodrio` in `iced_web`
  web/Cargo.toml
  web/src/lib.rs
  web/src/widget/button.rs
  web/src/widget/checkbox.rs
  web/src/widget/image.rs
  web/src/widget/radio.rs
  web/src/widget/text.rs
  web/src/widget/text_input.rs
Labels: feature, improvement

#442 Title bar support for `PaneGrid`
  examples/pane_grid/README.md
  examples/pane_grid/src/main.rs
  glow/src/widget/pane_grid.rs
  graphics/src/widget/container.rs
  graphics/src/widget/pane_grid.rs
  native/src/layout.rs
  native/src/renderer/null.rs
  native/src/widget/pane_grid.rs
  native/src/widget/pane_grid/configuration.rs
  native/src/widget/pane_grid/content.rs
  native/src/widget/pane_grid/state.rs
  native/src/widget/pane_grid/title_bar.rs
  wgpu/src/widget/pane_grid.rs
Labels: feature

#445 Fix panic on paste in TextInput after programmatic modification of contents
  native/src/widget/text_input.rs
  native/src/widget/text_input/cursor.rs
  native/src/widget/text_input/editor.rs
Labels: bug

#444 Overlay support and `PickList` widget
  Cargo.toml
  examples/README.md
  examples/game_of_life/src/main.rs
  examples/game_of_life/src/preset.rs
  examples/game_of_life/src/style.rs
  examples/pick_list/Cargo.toml
  examples/pick_list/README.md
  examples/pick_list/src/main.rs
  examples/todos/src/main.rs
  glow/src/backend.rs
  glow/src/widget.rs
  glow/src/widget/pick_list.rs
  graphics/fonts/Icons.ttf
  graphics/src/backend.rs
  graphics/src/font.rs
  graphics/src/lib.rs
  graphics/src/overlay.rs
  graphics/src/overlay/menu.rs
  graphics/src/renderer.rs
  graphics/src/widget.rs
  graphics/src/widget/pick_list.rs
  native/src/element.rs
  native/src/lib.rs
  native/src/overlay.rs
  native/src/overlay/element.rs
  native/src/overlay/menu.rs
  native/src/program/state.rs
  native/src/renderer.rs
  native/src/renderer/null.rs
  native/src/user_interface.rs
  native/src/widget.rs
  native/src/widget/column.rs
  native/src/widget/container.rs
  native/src/widget/pane_grid.rs
  native/src/widget/pane_grid/content.rs
  native/src/widget/pick_list.rs
  native/src/widget/row.rs
  native/src/widget/scrollable.rs
  native/src/widget/space.rs
  src/widget.rs
  style/src/lib.rs
  style/src/menu.rs
  style/src/pick_list.rs
  wgpu/src/backend.rs
  wgpu/src/widget.rs
  wgpu/src/widget/pick_list.rs
Labels: feature

#462 Update `glow` to `0.5` in `iced_glow`
  glow/Cargo.toml
  glow/src/quad.rs
  glow/src/triangle.rs
Labels: improvement

#463 Added `always_show_controls` method to TitleBar
  native/src/widget/pane_grid/title_bar.rs
Labels: feature
