Repository iced-rs/iced, pull requests merged in 2020-11, with the labels that each got.

#592 Fixes #591 DimensionsMismatch error message
  src/window/icon.rs
Labels: bug

#590 Fix lifetimes in `Layout::children`
  native/src/layout.rs
Labels: improvement

#600 update guillotiere to 0.6
  wgpu/Cargo.toml
Labels: improvement

#597 Rebuild widget tree only after an application update
  glutin/src/application.rs
  graphics/src/viewport.rs
  native/src/user_interface.rs
  winit/src/application.rs
  winit/src/application/state.rs
Labels: improvement

#598 Add textinput focus method
  native/src/widget/text_input.rs
Labels: feature

#608 Improve flexibility of `PaneGrid`
  core/src/keyboard/modifiers_state.rs
  examples/pane_grid/Cargo.toml
  examples/pane_grid/src/main.rs
  glow/src/widget/pane_grid.rs
  graphics/src/widget/pane_grid.rs
  native/src/subscription.rs
  native/src/subscription/events.rs
  native/src/widget/pane_grid.rs
  native/src/widget/pane_grid/content.rs
  native/src/widget/pane_grid/state.rs
  wgpu/src/widget/pane_grid.rs
Labels: feature

#610 Update dependencies
  examples/integration/Cargo.toml
  examples/todos/Cargo.toml
  examples/todos/src/main.rs
  examples/tour/Cargo.toml
  glow/Cargo.toml
  graphics/Cargo.toml
  graphics/src/triangle.rs
  wgpu/Cargo.toml
  wgpu/src/image.rs
  wgpu/src/image/vector.rs
  wgpu/src/quad.rs
  wgpu/src/triangle.rs
Labels: improvement

#614 Event capturing
  examples/bezier_tool/src/main.rs
  examples/game_of_life/src/main.rs
  examples/pane_grid/src/main.rs
  glutin/src/application.rs
  graphics/src/widget/canvas.rs
  graphics/src/widget/canvas/event.rs
  graphics/src/widget/canvas/program.rs
  native/src/element.rs
  native/src/event.rs
  native/src/lib.rs
  native/src/overlay.rs
  native/src/overlay/element.rs
  native/src/overlay/menu.rs
  native/src/program/state.rs
  native/src/runtime.rs
  native/src/subscription.rs
  native/src/subscription/events.rs
  native/src/user_interface.rs
  native/src/widget.rs
  native/src/widget/button.rs
  native/src/widget/checkbox.rs
  native/src/widget/column.rs
  native/src/widget/container.rs
  native/src/widget/pane_grid.rs
  native/src/widget/pane_grid/content.rs
  native/src/widget/pane_grid/title_bar.rs
  native/src/widget/pick_list.rs
  native/src/widget/radio.rs
  native/src/widget/row.rs
  native/src/widget/scrollable.rs
  native/src/widget/slider.rs
  native/src/widget/text_input.rs
  winit/src/application.rs
Labels: feature

#620 Disable dragging in `TextInput` after double click
  native/src/widget/text_input.rs
Labels: bug

#622 `QRCode` widget
  Cargo.toml
  examples/qr_code/Cargo.toml
  examples/qr_code/README.md
  examples/qr_code/src/main.rs
  glow/Cargo.toml
  glow/src/widget.rs
  glow/src/widget/qr_code.rs
  graphics/Cargo.toml
  graphics/src/widget.rs
  graphics/src/widget/qr_code.rs
  src/widget.rs
  wgpu/Cargo.toml
  wgpu/src/widget.rs
  wgpu/src/widget/qr_code.rs
Labels: feature

#628 Use `f32` for `border_width` and `border_radius`
  examples/custom_widget/src/main.rs
  examples/game_of_life/src/style.rs
  examples/pane_grid/src/main.rs
  examples/pokedex/src/main.rs
  examples/scrollable/src/style.rs
  examples/stopwatch/src/main.rs
  examples/styling/src/main.rs
  examples/todos/src/main.rs
  examples/tour/src/main.rs
  glow/src/shader/quad.vert
  graphics/src/layer.rs
  graphics/src/overlay/menu.rs
  graphics/src/primitive.rs
  graphics/src/renderer.rs
  graphics/src/widget/button.rs
  graphics/src/widget/container.rs
  graphics/src/widget/progress_bar.rs
  graphics/src/widget/radio.rs
  graphics/src/widget/rule.rs
  graphics/src/widget/scrollable.rs
  graphics/src/widget/slider.rs
  graphics/src/widget/text_input.rs
  style/src/button.rs
  style/src/checkbox.rs
  style/src/container.rs
  style/src/menu.rs
  style/src/pick_list.rs
  style/src/progress_bar.rs
  style/src/radio.rs
  style/src/rule.rs
  style/src/scrollable.rs
  style/src/slider.rs
  style/src/text_input.rs
  wgpu/src/shader/quad.vert
  wgpu/src/shader/quad.vert.spv
Labels: improvement

#627 Fix backwards `Frame::rotate` in `canvas`
  graphics/src/widget/canvas/frame.rs
Labels: bug

#629 Add `present_mode` field to `iced_wgpu::Settings`
  wgpu/src/settings.rs
  wgpu/src/window/compositor.rs
Labels: feature

#595 upgrade tokio to latest version(v0.3)
  Cargo.toml
  examples/download_progress/Cargo.toml
  examples/game_of_life/Cargo.toml
  examples/pokedex/Cargo.toml
  futures/Cargo.toml
  futures/src/executor.rs
  futures/src/executor/tokio.rs
  futures/src/executor/tokio_old.rs
  futures/src/lib.rs
  futures/src/time.rs
  src/executor.rs
  src/lib.rs
Labels: improvement

#605 This PR fixes a bug with select all (CMD + A on MacOS) when using a text_input.
  native/src/widget/text_input.rs
Labels: bug

#634 Add license to iced-graphics' Cargo.toml
  graphics/Cargo.toml
Labels: improvement

#527 Account for empty ranges in `Slider` and `ProgressBar`
  graphics/src/widget/progress_bar.rs
  graphics/src/widget/slider.rs
Labels: bug

#636 Update `ECOSYSTEM` and `ROADMAP`
  ECOSYSTEM.md
  README.md
  ROADMAP.md
  core/README.md
  core/src/lib.rs
  docs/graphs/core.dot
  docs/graphs/core.png
  docs/graphs/ecosystem.dot
  docs/graphs/ecosystem.png
  docs/graphs/foundations.png
  docs/graphs/generate.sh
  docs/graphs/iced.dot
  docs/graphs/iced.png
  docs/graphs/native.dot
  docs/graphs/native.png
  docs/graphs/web.dot
  docs/graphs/web.png
  docs/graphs/wgpu.dot
  docs/graphs/wgpu.png
  docs/graphs/winit.dot
  docs/graphs/winit.png
  futures/src/lib.rs
  glow/src/lib.rs
  glutin/README.md
  glutin/src/lib.rs
  graphics/Cargo.toml
  graphics/src/lib.rs
  native/README.md
  native/src/lib.rs
  style/src/lib.rs
  web/README.md
  web/src/lib.rs
  wgpu/README.md
  wgpu/src/lib.rs
  winit/README.md
  winit/src/lib.rs
Labels: improvement

#637 Release `0.2` — Canvas interactivity, overlay support, a renderer alternative, and more!
  Cargo.toml
  README.md
  core/Cargo.toml
  core/README.md
  futures/Cargo.toml
  futures/src/subscription.rs
  glow/Cargo.toml
  glow/src/widget/pane_grid.rs
  glutin/Cargo.toml
  graphics/Cargo.toml
  graphics/src/widget/pane_grid.rs
  native/Cargo.toml
  native/README.md
  native/src/user_interface.rs
  native/src/widget.rs
  src/application.rs
  src/lib.rs
  src/sandbox.rs
  style/Cargo.toml
  web/Cargo.toml
  web/README.md
  web/src/lib.rs
  wgpu/Cargo.toml
  wgpu/README.md
  winit/Cargo.toml
  winit/README.md
Labels: feature, improvement
