Repository iced-rs/iced, pull requests merged in 2020-12, with the labels that each got.

#658 Update `winit` and `glutin`
  glutin/Cargo.toml
  winit/Cargo.toml
  winit/src/conversion.rs
Labels: improvement

#57 Touch support
  core/src/mouse/event.rs
  native/src/event.rs
  native/src/lib.rs
  native/src/touch.rs
  native/src/widget/button.rs
  native/src/widget/checkbox.rs
  native/src/widget/radio.rs
  native/src/widget/scrollable.rs
  native/src/widget/slider.rs
  native/src/widget/text_input.rs
  winit/src/application/state.rs
  winit/src/conversion.rs
Labels: feature

#319 Add `ImagePane` widget
  .github/workflows/test.yml
  examples/pokedex/src/main.rs
  graphics/src/widget/image.rs
  graphics/src/widget/image/viewer.rs
  native/src/widget/image.rs
  native/src/widget/image/viewer.rs
  src/widget.rs
Labels: feature

#668 Propagate `Button` events to contents
  native/src/widget/button.rs
Labels: bug

#669 Update `resvg` and `font-kit`
  graphics/Cargo.toml
  wgpu/Cargo.toml
  wgpu/src/image/vector.rs
Labels: improvement

#657 Generic Element Content in Pane Grid TitleBar
  examples/pane_grid/src/main.rs
  graphics/src/widget/pane_grid.rs
  native/src/renderer/null.rs
  native/src/widget/pane_grid.rs
  native/src/widget/pane_grid/title_bar.rs
Labels: feature
