Repository iced-rs/iced, pull requests merged in 2020-05, with the labels that each got.

#200 Color Enhancements
  Cargo.toml
  core/Cargo.toml
  core/src/color.rs
  examples/README.md
  examples/color_palette/Cargo.toml
  examples/color_palette/README.md
  examples/color_palette/screenshot.png
  examples/color_palette/src/main.rs
Labels: feature, improvement

#345 Update `Radio` to have the same layout members and fns as `Checkbox`
  native/src/renderer/null.rs
  native/src/widget/radio.rs
  wgpu/src/renderer/widget/radio.rs
Labels: feature

#358 Implement `State::layout` and `State::with_content` in `pane_grid`
  native/src/widget/pane_grid.rs
  native/src/widget/pane_grid/content.rs
  native/src/widget/pane_grid/node.rs
  native/src/widget/pane_grid/state.rs
  wgpu/src/widget/pane_grid.rs
Labels: feature

#362 Align quads to physical pixels in `iced_wgpu`
  wgpu/src/shader/quad.vert
  wgpu/src/shader/quad.vert.spv
Labels: bug, improvement

#361 Proper Pane Grid spacing
  native/src/widget/pane_grid/axis.rs
  native/src/widget/pane_grid/node.rs
Labels: improvement

#359 Update `wgpu_glyph` and `glyph_brush`
  wgpu/Cargo.toml
  wgpu/src/backend.rs
  wgpu/src/text.rs
Labels: feature, improvement

#363 Make the Text widget Clone even if the Renderer isn't
  native/src/widget/text.rs
Labels: improvement

#369 Implement async `Compositor::request` in `iced_wgpu`
  wgpu/src/lib.rs
  wgpu/src/settings.rs
  wgpu/src/window/compositor.rs
Labels: feature
