Repository iced-rs/iced, pull requests merged in 2020-01, with the labels that each got.

#140 Mesh2D primitive for rendering arbitrary geometry in `iced_wgpu`
  examples/geometry.rs
  wgpu/src/lib.rs
  wgpu/src/primitive.rs
  wgpu/src/renderer.rs
  wgpu/src/shader/triangle.frag
  wgpu/src/shader/triangle.frag.spv
  wgpu/src/shader/triangle.vert
  wgpu/src/shader/triangle.vert.spv
  wgpu/src/triangle.rs
Labels: feature

#141 Progress bar widget
  core/src/background.rs
  examples/progress_bar.rs
  native/src/widget.rs
  native/src/widget/progress_bar.rs
  native/src/widget/text_input.rs
  src/native.rs
  web/src/widget/text_input.rs
  wgpu/src/renderer/widget.rs
  wgpu/src/renderer/widget/progress_bar.rs
  winit/src/conversion.rs
  winit/src/debug/basic.rs
Labels: feature

#139 Make `Row`, `Column`, `Text`, and `Checkbox` shrink by default
  examples/custom_widget.rs
  examples/events.rs
  examples/pokedex.rs
  examples/stopwatch.rs
  examples/svg.rs
  examples/todos.rs
  examples/tour.rs
  native/src/widget/checkbox.rs
  native/src/widget/column.rs
  native/src/widget/radio.rs
  native/src/widget/row.rs
  native/src/widget/svg.rs
  native/src/widget/text.rs
  native/src/widget/text_input.rs
  web/src/widget/column.rs
  web/src/widget/row.rs
  web/src/widget/text.rs
Labels: feature

#149 Window resized event
  native/src/event.rs
  native/src/lib.rs
  native/src/window.rs
  native/src/window/event.rs
  winit/src/application.rs
Labels: feature

#152 Fix flex layout cross-alignment when not filled
  native/src/layout/flex.rs
  native/src/layout/limits.rs
Labels: bug

#150 Move `Debugger` and `Windowed` traits
  native/src/element.rs
  native/src/layout.rs
  native/src/layout/debugger.rs
  native/src/lib.rs
  native/src/renderer.rs
  native/src/window.rs
  native/src/window/renderer.rs
  wgpu/src/renderer.rs
  wgpu/src/renderer/target.rs
  winit/src/application.rs
Labels: feature, improvement

#151 Make layout bounds explicit in `UserInterface`
  native/src/renderer.rs
  native/src/user_interface.rs
  wgpu/src/renderer.rs
  winit/src/application.rs
Labels: feature, improvement

#144 Add MS paint example
  Cargo.toml
  examples/bezier_tool.rs
Labels: improvement

#155 Remove Clone bound on Application::Message
  native/src/element.rs
  src/application.rs
  src/sandbox.rs
  web/src/bus.rs
  web/src/element.rs
  web/src/lib.rs
  web/src/widget/checkbox.rs
  web/src/widget/scrollable.rs
  web/src/widget/slider.rs
  web/src/widget/text_input.rs
Labels: feature, improvement

#161 Window modes
  src/application.rs
  src/lib.rs
  src/settings.rs
  src/window.rs
  src/window/mode.rs
  src/window/settings.rs
  winit/src/application.rs
  winit/src/conversion.rs
  winit/src/lib.rs
  winit/src/mode.rs
Labels: feature

#162 Window file events
  native/src/event.rs
  native/src/widget/column.rs
  native/src/widget/row.rs
  native/src/window/event.rs
  winit/src/application.rs
  winit/src/subscription.rs
Labels: feature

#165 Forbid unsafe code and Rust 2018 idioms
  core/src/lib.rs
  futures/src/lib.rs
  native/src/lib.rs
  src/lib.rs
  web/src/lib.rs
  wgpu/src/lib.rs
  winit/src/lib.rs
Labels: improvement

#166 Make `image` support optional in `iced_wgpu`
  Cargo.toml
  examples/pokedex/Cargo.toml
  examples/tour/Cargo.toml
  wgpu/Cargo.toml
  wgpu/src/image.rs
  wgpu/src/renderer/widget.rs
Labels: feature, improvement

#171 Enable custom fonts for text input
  native/src/renderer/null.rs
  native/src/widget/text_input.rs
  wgpu/src/renderer/widget/text_input.rs
Labels: feature
