Repository iced-rs/iced, pull requests merged in 2020-03, with the labels that each got.

#214 Implement text support in canvas widget
  core/src/point.rs
  core/src/vector.rs
  examples/bezier_tool/src/main.rs
  examples/geometry/src/main.rs
  wgpu/src/primitive.rs
  wgpu/src/renderer.rs
  wgpu/src/triangle.rs
  wgpu/src/widget/canvas.rs
  wgpu/src/widget/canvas/frame.rs
  wgpu/src/widget/canvas/layer.rs
  wgpu/src/widget/canvas/layer/cache.rs
  wgpu/src/widget/canvas/text.rs
Labels: feature

#215 Update `winit` to `0.22`
  examples/integration/src/main.rs
  winit/Cargo.toml
  winit/src/application.rs
Labels: improvement

#220 Instantiate Column and Row with children
  native/src/widget/column.rs
  native/src/widget/row.rs
  web/src/widget/column.rs
  web/src/widget/row.rs
Labels: feature

#224 Pane grid widget
  Cargo.toml
  core/src/keyboard.rs
  core/src/keyboard/key_code.rs
  core/src/keyboard/modifiers_state.rs
  core/src/lib.rs
  core/src/point.rs
  examples/README.md
  examples/pane_grid/Cargo.toml
  examples/pane_grid/README.md
  examples/pane_grid/src/main.rs
  futures/src/subscription.rs
  native/src/element.rs
  native/src/input/keyboard.rs
  native/src/input/keyboard/modifiers_state.rs
  native/src/lib.rs
  native/src/mouse_cursor.rs
  native/src/widget.rs
  native/src/widget/column.rs
  native/src/widget/pane_grid.rs
  native/src/widget/pane_grid/axis.rs
  native/src/widget/pane_grid/direction.rs
  native/src/widget/pane_grid/node.rs
  native/src/widget/pane_grid/pane.rs
  native/src/widget/pane_grid/split.rs
  native/src/widget/pane_grid/state.rs
  src/keyboard.rs
  src/lib.rs
  src/widget.rs
  web/src/lib.rs
  wgpu/src/renderer/widget.rs
  wgpu/src/renderer/widget/pane_grid.rs
  wgpu/src/renderer/widget/scrollable.rs
  wgpu/src/widget.rs
  wgpu/src/widget/canvas/layer/cache.rs
  wgpu/src/widget/pane_grid.rs
  winit/src/conversion.rs
Labels: feature

#229 Add workflow to check format in CI
  .github/workflows/format.yml
  rustfmt.toml
Labels: improvement

#232 Add example for download with progress tracking
  Cargo.toml
  examples/README.md
  examples/download_progress/Cargo.toml
  examples/download_progress/README.md
  examples/download_progress/src/download.rs
  examples/download_progress/src/main.rs
Labels: improvement

#202 Text Selection for text_input widget
  examples/styling/src/main.rs
  native/src/input/mouse.rs
  native/src/input/mouse/click.rs
  native/src/renderer/null.rs
  native/src/widget/text_input.rs
  native/src/widget/text_input/cursor.rs
  native/src/widget/text_input/editor.rs
  native/src/widget/text_input/value.rs
  style/src/text_input.rs
  wgpu/src/renderer/widget/text_input.rs
Labels: feature

#234 Improve compatibility of `iced_futures`
  futures/src/command.rs
  futures/src/command/native.rs
  futures/src/command/web.rs
  futures/src/lib.rs
  futures/src/subscription.rs
  futures/src/subscription/tracker.rs
  native/src/subscription/events.rs
Labels: feature, improvement

#236 Genericize `From` implementation for `svg::Handle`
  native/src/widget/svg.rs
Labels: feature, improvement

#239 Convert `WindowEvent` from a reference in `iced_winit`
  examples/integration/src/main.rs
  winit/src/application.rs
  winit/src/conversion.rs
Labels: feature, improvement

#240 remove explicit lifetimes in integration example
  examples/integration/src/controls.rs
Labels: improvement

#245 refactor: remove not mandatories 'static lifetimes
  Cargo.toml
  native/src/widget/button.rs
  native/src/widget/checkbox.rs
  native/src/widget/column.rs
  native/src/widget/container.rs
  native/src/widget/image.rs
  native/src/widget/pane_grid.rs
  native/src/widget/progress_bar.rs
  native/src/widget/radio.rs
  native/src/widget/row.rs
  native/src/widget/scrollable.rs
  native/src/widget/slider.rs
  native/src/widget/space.rs
  native/src/widget/svg.rs
  native/src/widget/text.rs
  native/src/widget/text_input.rs
Labels: improvement

#247 Implement `svg::Handle::from_memory`
  examples/svg/Cargo.toml
  examples/svg/src/main.rs
  native/src/widget/image.rs
  native/src/widget/svg.rs
  wgpu/src/image/vector.rs
Labels: feature

#248 Implement `padding` support for `Container`
  examples/clock/src/main.rs
  examples/pane_grid/src/main.rs
  examples/pokedex/src/main.rs
  examples/svg/src/main.rs
  native/src/layout/flex.rs
  native/src/widget/container.rs
  web/src/widget/container.rs
Labels: feature

#246 Application flags
  examples/clock/src/main.rs
  examples/download_progress/src/main.rs
  examples/events/src/main.rs
  examples/pokedex/src/main.rs
  examples/solar_system/src/main.rs
  examples/stopwatch/src/main.rs
  examples/todos/src/main.rs
  src/application.rs
  src/executor.rs
  src/sandbox.rs
  src/settings.rs
  web/src/lib.rs
  winit/src/application.rs
  winit/src/settings.rs
Labels: feature

#249 Add Ctrl+Backspace text field behaviour
  native/src/widget/text_input.rs
Labels: improvement
