Repository iced-rs/iced, pull requests merged in 2021-01, with the labels that each got.

#678 Split highlight for the `PaneGrid` widget
  glow/src/widget/pane_grid.rs
  graphics/src/widget/pane_grid.rs
  native/src/renderer/null.rs
  native/src/widget/pane_grid.rs
  native/src/widget/pane_grid/content.rs
  native/src/widget/pane_grid/title_bar.rs
  style/src/lib.rs
  style/src/pane_grid.rs
  wgpu/src/widget/pane_grid.rs
Labels: feature

#672 Update tokio to v1.0
  examples/game_of_life/Cargo.toml
  futures/Cargo.toml
  futures/src/time.rs
Labels: feature, improvement

#694 Capture relevant events in `image::Viewer`
  native/src/widget/image/viewer.rs
Labels: bug

#700 Fix `physical_width` getter incorrectly returning the height
  graphics/src/viewport.rs
Labels: bug

#699 Add `smol` async runtime support
  CHANGELOG.md
  Cargo.toml
  examples/stopwatch/Cargo.toml
  futures/Cargo.toml
  futures/src/executor.rs
  futures/src/executor/smol.rs
  futures/src/lib.rs
  futures/src/time.rs
  src/executor.rs
  src/lib.rs
Labels: feature

#710 update example description at sandbox's documentation
  src/sandbox.rs
Labels: improvement

#719 Make iced::Error Send + Sync
  src/error.rs
Labels: feature

#720 impl Clone and Copy for all Style types in iced_style
  style/src/button.rs
  style/src/checkbox.rs
  style/src/progress_bar.rs
  style/src/radio.rs
Labels: feature
