Repository iced-rs/iced, pull requests merged in 2021-11, with the labels that each got.

#1109 Fix color issue with Debugger::explain implementation for Renderer
  graphics/src/renderer.rs
Labels: bug

#1106 Remove unnecessary String allocation
  README.md
  examples/scrollable/src/main.rs
  examples/styling/src/main.rs
  examples/todos/src/main.rs
  examples/tour/src/main.rs
Labels: improvement

#1117 Disable default features in twox-hash dependency.
  native/Cargo.toml
Labels: improvement

#1116 Add checkbox text_color styling
  examples/styling/src/main.rs
  native/src/widget/checkbox.rs
  style/src/checkbox.rs
Labels: feature

#1114 Don't rebroadcast redundant slider messages
  native/src/widget/slider.rs
Labels: improvement

#1121 Fix a few doc links
  src/settings.rs
  winit/src/application.rs
Labels: improvement

#1124 Fix implementation of `Widget::mouse_interaction` for `PaneGrid`
  native/src/widget/pane_grid.rs
Labels: bug

#1125 Fix overflow of graphics primitives in overlays
  native/src/user_interface.rs
Labels: bug

#1118 Native web fixes.
  futures/src/lib.rs
  native/src/subscription.rs
  native/src/subscription/events.rs
Labels: improvement

#1112 Application::run returns on native platforms
  glutin/src/application.rs
  src/application.rs
  winit/src/application.rs
Labels: feature
