Repository iced-rs/iced, pull requests merged in 2021-09, with the labels that each got.

#788 feat(web): Support in-memory image data
  web/Cargo.toml
  web/src/widget/image.rs
Labels: feature

#683 Update `lyon` to `0.17` in `iced_graphics`
  graphics/Cargo.toml
  graphics/src/widget/canvas/frame.rs
  graphics/src/widget/canvas/path.rs
  graphics/src/widget/canvas/path/builder.rs
Labels: improvement

#1021 Fix window holes behind transparent objects
  glow/src/window/compositor.rs
Labels: bug

#1019 Platform-specific `Command` implementations
  examples/clock/src/main.rs
  examples/download_progress/src/main.rs
  examples/events/src/main.rs
  examples/game_of_life/src/main.rs
  examples/integration_opengl/src/controls.rs
  examples/integration_wgpu/src/controls.rs
  examples/menu/src/main.rs
  examples/pane_grid/src/main.rs
  examples/pokedex/src/main.rs
  examples/solar_system/src/main.rs
  examples/stopwatch/src/main.rs
  examples/todos/src/main.rs
  examples/url_handler/src/main.rs
  futures/src/command.rs
  futures/src/runtime.rs
  glutin/src/application.rs
  glutin/src/lib.rs
  native/src/clipboard.rs
  native/src/command.rs
  native/src/command/action.rs
  native/src/lib.rs
  native/src/program.rs
  native/src/program/state.rs
  native/src/window.rs
  native/src/window/action.rs
  native/src/window/event.rs
  src/application.rs
  src/clipboard.rs
  src/lib.rs
  src/sandbox.rs
  src/window.rs
  web/src/clipboard.rs
  web/src/command.rs
  web/src/command/action.rs
  web/src/lib.rs
  winit/src/application.rs
  winit/src/clipboard.rs
  winit/src/lib.rs
  winit/src/window.rs
Labels: feature

#1046 Use `Option` to encode empty text case in hit test methods
  core/src/text.rs
  glow/src/backend.rs
  glow/src/text.rs
  graphics/src/backend.rs
  graphics/src/widget/text.rs
  native/src/renderer/null.rs
  native/src/widget/text.rs
  native/src/widget/text_input.rs
  wgpu/src/backend.rs
  wgpu/src/text.rs
Labels: bug

#1047 Revert system menus support
  Cargo.toml
  core/src/keyboard.rs
  core/src/keyboard/hotkey.rs
  core/src/lib.rs
  core/src/menu.rs
  examples/game_of_life/src/main.rs
  examples/game_of_life/src/preset.rs
  examples/menu/Cargo.toml
  examples/menu/src/main.rs
  glutin/Cargo.toml
  glutin/src/application.rs
  native/src/lib.rs
  native/src/program.rs
  src/application.rs
  src/lib.rs
  src/sandbox.rs
  web/src/lib.rs
  winit/Cargo.toml
  winit/src/application.rs
  winit/src/application/state.rs
  winit/src/conversion.rs
Labels: feature

#1049 CI: Run a Windows application without starting the shell too
  .github/workflows/build.yml
Labels: feature

#1044 Add Align::Fill variant
  core/src/align.rs
  core/src/alignment.rs
  core/src/lib.rs
  examples/bezier_tool/src/main.rs
  examples/color_palette/src/main.rs
  examples/counter/src/main.rs
  examples/custom_widget/src/main.rs
  examples/download_progress/src/main.rs
  examples/events/src/main.rs
  examples/game_of_life/src/main.rs
  examples/geometry/src/main.rs
  examples/integration_opengl/src/controls.rs
  examples/integration_wgpu/src/controls.rs
  examples/pane_grid/src/main.rs
  examples/pick_list/src/main.rs
  examples/pokedex/src/main.rs
  examples/qr_code/src/main.rs
  examples/stopwatch/src/main.rs
  examples/styling/src/main.rs
  examples/todos/src/main.rs
  examples/tooltip/src/main.rs
  examples/tour/src/main.rs
  glow/src/backend.rs
  glow/src/lib.rs
  graphics/src/layer.rs
  graphics/src/lib.rs
  graphics/src/overlay/menu.rs
  graphics/src/primitive.rs
  graphics/src/widget/canvas/text.rs
  graphics/src/widget/checkbox.rs
  graphics/src/widget/pick_list.rs
  graphics/src/widget/text.rs
  graphics/src/widget/text_input.rs
  native/src/layout/flex.rs
  native/src/layout/node.rs
  native/src/lib.rs
  native/src/renderer/null.rs
  native/src/widget/checkbox.rs
  native/src/widget/column.rs
  native/src/widget/container.rs
  native/src/widget/radio.rs
  native/src/widget/row.rs
  native/src/widget/scrollable.rs
  native/src/widget/text.rs
  native/src/widget/toggler.rs
  src/lib.rs
  web/src/css.rs
  web/src/lib.rs
  web/src/widget/column.rs
  web/src/widget/container.rs
  web/src/widget/row.rs
  web/src/widget/scrollable.rs
  web/src/widget/text.rs
  wgpu/src/backend.rs
Labels: feature

#1060 Update `resvg` to `0.18` in `iced_wgpu`
  wgpu/Cargo.toml
  wgpu/src/image/vector.rs
Labels: improvement
