Repository iced-rs/iced, pull requests merged in 2021-07, with the labels that each got.

#953 Fix implementation of `Widget::overlay` for `pane_grid::TitleBar`
  native/src/widget/pane_grid/title_bar.rs
Labels: bug

#945 feat: add menus
  Cargo.toml
  core/Cargo.toml
  core/src/keyboard.rs
  core/src/keyboard/hotkey.rs
  core/src/keyboard/modifiers.rs
  core/src/lib.rs
  core/src/menu.rs
  examples/game_of_life/src/main.rs
  examples/game_of_life/src/preset.rs
  examples/menu/Cargo.toml
  examples/menu/src/main.rs
  examples/pane_grid/src/main.rs
  glutin/Cargo.toml
  glutin/src/application.rs
  native/src/lib.rs
  native/src/program.rs
  native/src/widget/text_input.rs
  src/application.rs
  src/lib.rs
  src/sandbox.rs
  web/src/lib.rs
  winit/Cargo.toml
  winit/src/application.rs
  winit/src/application/state.rs
  winit/src/conversion.rs
Labels: feature

#952 Use ceil on svg dimensions, fix svg memory usage ref #841
  wgpu/src/image/vector.rs
Labels: bug

#956 Open the todos example via double-click on MacOS
  .github/workflows/build.yml
Labels: improvement

#929 feat: add position to window settings
  examples/game_of_life/src/main.rs
  src/window.rs
  src/window/position.rs
  src/window/settings.rs
  winit/src/conversion.rs
  winit/src/lib.rs
  winit/src/position.rs
  winit/src/settings.rs
Labels: feature

#885 image viewer: Only calculate viewport based width/length for Length::Unit|Shrink
  native/src/widget/image/viewer.rs
Labels: feature

#914 feat: expose draw_cache_multithread as a feature
  glow/src/backend.rs
  glow/src/settings.rs
  glow/src/text.rs
  src/application.rs
  src/settings.rs
  wgpu/src/backend.rs
  wgpu/src/settings.rs
  wgpu/src/text.rs
Labels: feature

#888 Add Placeholders to PickList
  examples/game_of_life/src/style.rs
  examples/pick_list/src/main.rs
  graphics/src/widget/pick_list.rs
  native/src/widget/pick_list.rs
  style/src/pick_list.rs
Labels: feature

#776 Added `select_all` method to `TextInput`.
  examples/todos/src/main.rs
  native/src/widget/text_input.rs
  web/src/widget/text_input.rs
Labels: feature

#872 add scrolling to pick_lists
  native/src/widget/pick_list.rs
Labels: feature

#965 Add window::Event::Moved
  native/src/window/event.rs
  winit/src/conversion.rs
Labels: feature

#966 Allow `PickList` selection with mouse scroll only if command is pressed
  native/src/widget/pick_list.rs
Labels: bug, improvement

#967 Introduce `COMMAND` constant to `keyboard::Modifiers`
  core/src/keyboard/modifiers.rs
Labels: feature

#971 fix: allow titlebar overlays to close when dragging pane
  native/src/widget/pane_grid.rs
  native/src/widget/pane_grid/content.rs
Labels: bug
