Repository iced-rs/iced, pull requests merged in 2021-05, with the labels that each got.

#851 Fix `Scrollable` scrollbar being rendered behind contents
  examples/scrollable/Cargo.toml
  examples/scrollable/src/main.rs
  graphics/src/widget/scrollable.rs
Labels: bug

#868 Provide `compatible_surface` in `iced_wgpu::Compositor`
  graphics/src/window/compositor.rs
  rustfmt.toml
  wgpu/src/window/compositor.rs
  winit/src/application.rs
Labels: bug

#877 Change examples to point to 0.3 examples, not 0.2
  src/lib.rs
Labels: improvement

#875 This commit optimizes the algorithm used to convert rgba pixels into bgra pixels for SVG's.
  wgpu/src/image/vector.rs
Labels: improvement

#831 Added text color and font options for native radio and checkbox
  native/src/widget/checkbox.rs
  native/src/widget/radio.rs
Labels: feature

#886 pick_list: fix layouting not respecting fonts
  native/src/widget/pick_list.rs
Labels: bug

#830 Upgrade wgpu
  examples/integration/src/scene.rs
  examples/pokedex/src/main.rs
  examples/styling/src/main.rs
  native/src/widget/text_input/cursor.rs
  native/src/widget/text_input/editor.rs
  src/window/icon.rs
  wgpu/Cargo.toml
  wgpu/src/image.rs
  wgpu/src/image/atlas.rs
  wgpu/src/quad.rs
  wgpu/src/shader/blit.frag
  wgpu/src/shader/blit.frag.spv
  wgpu/src/shader/blit.vert
  wgpu/src/shader/blit.vert.spv
  wgpu/src/shader/blit.wgsl
  wgpu/src/shader/image.frag
  wgpu/src/shader/image.frag.spv
  wgpu/src/shader/image.vert
  wgpu/src/shader/image.vert.spv
  wgpu/src/shader/image.wgsl
  wgpu/src/shader/quad.frag
  wgpu/src/shader/quad.frag.spv
  wgpu/src/shader/quad.vert
  wgpu/src/shader/quad.vert.spv
  wgpu/src/shader/quad.wgsl
  wgpu/src/shader/triangle.frag
  wgpu/src/shader/triangle.frag.spv
  wgpu/src/shader/triangle.vert
  wgpu/src/shader/triangle.vert.spv
  wgpu/src/shader/triangle.wgsl
  wgpu/src/triangle.rs
  wgpu/src/triangle/msaa.rs
  wgpu/src/window/compositor.rs
Labels: feature

#892 PaneGrid Events in Title Bar Area
  examples/pane_grid/src/main.rs
  graphics/src/widget/pane_grid.rs
  native/src/widget/pane_grid/title_bar.rs
Labels: feature
