Repository iced-rs/iced, pull requests merged in 2021-12, with the labels that each got.

#1131 `iced_lazy` and `Component` trait
  Cargo.toml
  examples/component/Cargo.toml
  examples/component/src/main.rs
  graphics/src/widget/canvas.rs
  lazy/Cargo.toml
  lazy/src/component.rs
  lazy/src/lib.rs
  native/src/element.rs
  native/src/lib.rs
  native/src/overlay.rs
  native/src/overlay/element.rs
  native/src/overlay/menu.rs
  native/src/shell.rs
  native/src/user_interface.rs
  native/src/widget.rs
  native/src/widget/button.rs
  native/src/widget/checkbox.rs
  native/src/widget/column.rs
  native/src/widget/container.rs
  native/src/widget/image/viewer.rs
  native/src/widget/pane_grid.rs
  native/src/widget/pane_grid/content.rs
  native/src/widget/pane_grid/title_bar.rs
  native/src/widget/pick_list.rs
  native/src/widget/radio.rs
  native/src/widget/row.rs
  native/src/widget/scrollable.rs
  native/src/widget/slider.rs
  native/src/widget/text_input.rs
  native/src/widget/toggler.rs
  native/src/widget/tooltip.rs
Labels: feature

#1140 Include alignment in the container layout hash
  core/src/alignment.rs
  native/src/widget/container.rs
Labels: bug

#1142 Remove unused fields
  examples/pokedex/src/main.rs
  examples/solar_system/src/main.rs
  native/src/widget/scrollable.rs
  wgpu/src/backend.rs
Labels: improvement

#1149 Fix `Widget::height` for `Component`
  lazy/src/component.rs
Labels: bug

#1150 Make TextInput emit a Submit message when the key NumpadEnter is pressed
  native/src/widget/text_input.rs
Labels: improvement

#1157 Fix path to ferris.png
  examples/tour/src/main.rs
Labels: bug

#1155 Decouple `image::Handle` from `iced_native` and lower trait bound on `text::Renderer::Font`
  graphics/src/widget/image.rs
  native/src/image.rs
  native/src/overlay/menu.rs
  native/src/text.rs
  native/src/widget/checkbox.rs
  native/src/widget/image.rs
  native/src/widget/image/viewer.rs
  native/src/widget/pick_list.rs
  native/src/widget/radio.rs
  native/src/widget/text.rs
  native/src/widget/text_input.rs
  native/src/widget/toggler.rs
Labels: improvement

#1154 Implement `overlay` for `Component`
  lazy/src/component.rs
  native/src/layout/node.rs
Labels: improvement

#1169 fix: nested component layout invalidation
  lazy/src/component.rs
Labels: bug
