Repository iced-rs/iced, pull requests merged in 2021-08, with the labels that each got.

#980 Fix glow and multiple windows usage
  glutin/src/application.rs
Labels: bug

#978 wgpu: Use the preferred texture format of the surface
  examples/integration/src/main.rs
  wgpu/src/backend.rs
  wgpu/src/settings.rs
  wgpu/src/window/compositor.rs
Labels: improvement

#667 Don't panic when wgpu swapchain frame is outdated
  examples/integration/src/main.rs
  graphics/src/window.rs
  graphics/src/window/compositor.rs
  wgpu/src/window/compositor.rs
  winit/src/application.rs
Labels: bug

#599 Add wayland app_id
  glutin/src/application.rs
  src/settings.rs
  winit/src/application.rs
  winit/src/settings.rs
Labels: feature

#517 iced_web: Add an option to select the element
  web/src/lib.rs
Labels: feature

#652 text_input: Do not capture Tab/Up/Down keys
  native/src/widget/text_input.rs
Labels: bug

#994 tweak default rule style
  style/src/rule.rs
Labels: improvement

#617 Add integration_gl example
  Cargo.toml
  examples/README.md
  examples/integration_opengl/Cargo.toml
  examples/integration_opengl/README.md
  examples/integration_opengl/src/controls.rs
  examples/integration_opengl/src/main.rs
  examples/integration_opengl/src/scene.rs
  examples/integration_wgpu/Cargo.toml
  examples/integration_wgpu/README.md
  examples/integration_wgpu/src/controls.rs
  examples/integration_wgpu/src/main.rs
  examples/integration_wgpu/src/scene.rs
  examples/integration_wgpu/src/shader/frag.spv
  examples/integration_wgpu/src/shader/vert.spv
  glow/src/lib.rs
Labels: improvement

#1000 wgpu: Update to 0.10
  Cargo.toml
  examples/integration_wgpu/Cargo.toml
  examples/integration_wgpu/src/main.rs
  examples/integration_wgpu/src/scene.rs
  graphics/src/window.rs
  graphics/src/window/compositor.rs
  wgpu/Cargo.toml
  wgpu/src/image.rs
  wgpu/src/image/atlas.rs
  wgpu/src/quad.rs
  wgpu/src/settings.rs
  wgpu/src/triangle.rs
  wgpu/src/triangle/msaa.rs
  wgpu/src/window/compositor.rs
  winit/src/application.rs
Labels: bug, improvement
