Repository iced-rs/iced, pull requests merged in 2022-09, with the labels that each got.

#1429 Remove old pure feature from docs.rs build metadata
  Cargo.toml
Labels: bug

#1434 Update docs for running `integration_wgpu` example
  examples/integration_wgpu/README.md
Labels: documentation

#1433 Update docs for renamed integration examples
  native/src/user_interface.rs
Labels: documentation

#1437 fix: sync size of window and viewport
  winit/src/application/state.rs
Labels: bug, shell

#1425 Make `overlay::menu` accessible
  src/lib.rs
  src/overlay.rs
Labels: bug, improvement, widget

#1107 Text content by cow
  examples/todos/src/main.rs
  native/src/element.rs
  native/src/widget/helpers.rs
  native/src/widget/text.rs
  native/src/widget/tooltip.rs
  src/widget.rs
Labels: improvement, text, widget

#1136 Implement sierpinski-triangle example
  Cargo.toml
  examples/README.md
  examples/sierpinski_triangle/Cargo.toml
  examples/sierpinski_triangle/README.md
  examples/sierpinski_triangle/src/main.rs
Labels: improvement

#1444 Fix latest `clippy` lints
  lazy/src/cache.rs
  native/src/widget/pick_list.rs
  native/src/widget/text_input.rs
Labels: improvement

#1227 `color!` macro
  core/src/color.rs
  native/src/lib.rs
  src/lib.rs
Labels: improvement, developer experience

#1196 Add application feature, which allows to build freestanding wgpu app
  Cargo.toml
  winit/Cargo.toml
  winit/src/lib.rs
Labels: improvement, shell

#1230 Pass ignored events to program
  native/src/program/state.rs
Labels: improvement, feature, shell
