Repository iced-rs/iced, pull requests merged in 2022-08, with the labels that each got.

#1396 Allow specification of `border_radius` for `pick_list::Menu`
  native/src/overlay/menu.rs
  style/src/menu.rs
  style/src/theme.rs
Labels: improvement

#1399 Widget Operations
  examples/scrollable/src/main.rs
  examples/todos/Cargo.toml
  examples/todos/src/main.rs
  examples/tour/src/main.rs
  examples/websocket/Cargo.toml
  examples/websocket/src/main.rs
  glutin/src/application.rs
  native/src/command.rs
  native/src/command/action.rs
  native/src/element.rs
  native/src/overlay.rs
  native/src/overlay/element.rs
  native/src/user_interface.rs
  native/src/widget.rs
  native/src/widget/action.rs
  native/src/widget/button.rs
  native/src/widget/column.rs
  native/src/widget/container.rs
  native/src/widget/helpers.rs
  native/src/widget/id.rs
  native/src/widget/operation.rs
  native/src/widget/operation/focusable.rs
  native/src/widget/operation/scrollable.rs
  native/src/widget/row.rs
  native/src/widget/scrollable.rs
  native/src/widget/text_input.rs
  src/lib.rs
  src/widget.rs
  winit/src/application.rs
Labels: feature, widget, shell

#1402 Impl operate for Component widget
  lazy/src/component.rs
Labels: improvement, widget

#1409 Relax `Fn` trait bounds in `Command` & `Action`
  native/src/command.rs
Labels: feature, shell

#1405 Fix Tooltip inside Scrollable
  native/src/widget/tooltip.rs
Labels: bug, feature, widget

#1389 Replace `window::Mode` with window commands
  glutin/src/application.rs
  native/src/command/action.rs
  native/src/window.rs
  native/src/window/action.rs
  native/src/window/mode.rs
  src/application.rs
  src/window.rs
  src/window/settings.rs
  winit/src/application.rs
  winit/src/application/state.rs
  winit/src/conversion.rs
  winit/src/lib.rs
  winit/src/mode.rs
  winit/src/settings.rs
  winit/src/window.rs
Labels: bug, improvement, shell

#1421 Fix incorrect layout in `mouse_interaction` for `Tooltip`
  native/src/widget/tooltip.rs
Labels: bug

#1422 Fix invisible window on Windows
  glutin/src/application.rs
  winit/src/application.rs
  winit/src/settings.rs
Labels: bug

#1423 Reintroduce `Element::explain`
  examples/tour/src/main.rs
  native/src/element.rs
Labels: bug

#1424 When pane grid title bar is cramped, still show content until hover and allow dragging where content would've been
  native/src/widget/pane_grid/title_bar.rs
Labels: improvement, widget

#1410 Update `winit` to `0.27` and `glutin` to `0.29`
  glutin/Cargo.toml
  glutin/src/application.rs
  winit/Cargo.toml
  winit/src/application.rs
  winit/src/settings.rs
  winit/src/settings/windows.rs
Labels: improvement, feature, shell
