Repository iced-rs/iced, pull requests merged in 2022-11, with the labels that each got.

#1462 Update `wgpu` to `0.14` and `wgpu_glyph` to `0.18`
  examples/integration_wgpu/src/main.rs
  graphics/Cargo.toml
  graphics/src/window/compositor.rs
  wgpu/Cargo.toml
  wgpu/src/window/compositor.rs
Labels: improvement, feature

#1497 Use `once_cell` instead of `lazy_static`
  examples/todos/Cargo.toml
  examples/todos/src/main.rs
  examples/websocket/Cargo.toml
  examples/websocket/src/main.rs
  style/Cargo.toml
  style/src/theme/palette.rs
Labels: improvement

#1471 feat: Additional actions for window controls
  native/src/window/action.rs
  winit/src/application.rs
  winit/src/window.rs
Labels: feature, shell

#1502 fix: enable `application` feature required in `iced_glutin`
  glutin/Cargo.toml
Labels: bug

#1400 `Lazy` widget
  Cargo.toml
  examples/cached/Cargo.toml
  examples/cached/src/main.rs
  examples/lazy/Cargo.toml
  examples/lazy/src/main.rs
  lazy/src/lazy.rs
  lazy/src/lib.rs
  native/src/widget/text_input.rs
Labels: feature, widget

#1432 Add custom palette to built in theme
  examples/scrollable/src/main.rs
  examples/styling/src/main.rs
  style/src/theme.rs
  style/src/theme/palette.rs
Labels: feature, styling

#1448 Add linear gradient support to canvas widget
  Cargo.toml
  examples/arc/src/main.rs
  examples/clock/src/main.rs
  examples/geometry/Cargo.toml
  examples/geometry/README.md
  examples/geometry/src/main.rs
  examples/modern_art/Cargo.toml
  examples/modern_art/src/main.rs
  examples/multitouch/src/main.rs
  examples/solar_system/src/main.rs
  glow/src/backend.rs
  glow/src/quad/compatibility.rs
  glow/src/quad/core.rs
  glow/src/shader/common/gradient.frag
  glow/src/shader/common/triangle.frag
  glow/src/shader/common/triangle.vert
  glow/src/triangle.rs
  glow/src/triangle/gradient.rs
  glow/src/triangle/solid.rs
  glow/src/window/compositor.rs
  graphics/Cargo.toml
  graphics/src/gradient.rs
  graphics/src/gradient/linear.rs
  graphics/src/layer.rs
  graphics/src/layer/image.rs
  graphics/src/layer/mesh.rs
  graphics/src/layer/quad.rs
  graphics/src/layer/text.rs
  graphics/src/lib.rs
  graphics/src/primitive.rs
  graphics/src/transformation.rs
  graphics/src/triangle.rs
  graphics/src/widget/canvas.rs
  graphics/src/widget/canvas/fill.rs
  graphics/src/widget/canvas/frame.rs
  graphics/src/widget/canvas/stroke.rs
  wgpu/Cargo.toml
  wgpu/src/backend.rs
  wgpu/src/buffer.rs
  wgpu/src/buffer/dynamic.rs
  wgpu/src/buffer/static.rs
  wgpu/src/lib.rs
  wgpu/src/shader/gradient.wgsl
  wgpu/src/shader/solid.wgsl
  wgpu/src/triangle.rs
  wgpu/src/triangle/gradient.rs
  wgpu/src/triangle/solid.rs
Labels: feature, widget, rendering, wgpu, canvas

#1443 Allow to replace an element instead of append to body for web rendering
  winit/src/application.rs
  winit/src/settings.rs
  winit/src/settings/macos.rs
  winit/src/settings/wasm.rs
  winit/src/settings/windows.rs
Labels: feature, web

#1453 Use `Cow<'static, [u8]>` in image/svg, add constructors taking &[u8]`
  native/src/image.rs
  native/src/svg.rs
Labels: improvement, widget, image, svg

#1485 Glow image rendering support; move image/svg code to iced_graphics
  Cargo.toml
  glow/Cargo.toml
  glow/src/backend.rs
  glow/src/image.rs
  glow/src/image/storage.rs
  glow/src/lib.rs
  glow/src/shader/common/image.frag
  glow/src/shader/common/image.vert
  graphics/Cargo.toml
  graphics/src/backend.rs
  graphics/src/image.rs
  graphics/src/image/raster.rs
  graphics/src/image/storage.rs
  graphics/src/image/vector.rs
  graphics/src/lib.rs
  graphics/src/renderer.rs
  native/src/image.rs
  native/src/svg.rs
  native/src/widget/image.rs
  native/src/widget/image/viewer.rs
  native/src/widget/svg.rs
  wgpu/Cargo.toml
  wgpu/src/backend.rs
  wgpu/src/image.rs
  wgpu/src/image/atlas.rs
  wgpu/src/image/atlas/allocation.rs
  wgpu/src/image/atlas/allocator.rs
  wgpu/src/image/atlas/entry.rs
  wgpu/src/lib.rs
Labels: widget, rendering, image, wgpu

#1507 Don't convert svg to BGRA before passing to shader
  graphics/src/image/vector.rs
Labels: bug, rendering, image

#1505 Combine `glow_default_system_font` and `default_system_font` features
  Cargo.toml
Labels: improvement, developer experience

#1494 Constrain padding to resolved inner / outer widget sizes
  core/src/padding.rs
  core/src/size.rs
  native/src/widget/button.rs
  native/src/widget/container.rs
  native/src/widget/text_input.rs
Labels: improvement, widget, layout

#1504 Add pane maximize / restore for `PaneGrid`
  examples/pane_grid/src/main.rs
  native/src/widget/pane_grid.rs
  native/src/widget/pane_grid/state.rs
Labels: feature, widget, layout

#1519 Built-in `Theme` customization
  examples/solar_system/src/main.rs
  native/src/overlay/menu.rs
  native/src/widget/button.rs
  native/src/widget/checkbox.rs
  native/src/widget/container.rs
  native/src/widget/helpers.rs
  native/src/widget/pane_grid.rs
  native/src/widget/pane_grid/content.rs
  native/src/widget/pane_grid/title_bar.rs
  native/src/widget/pick_list.rs
  native/src/widget/progress_bar.rs
  native/src/widget/radio.rs
  native/src/widget/rule.rs
  native/src/widget/scrollable.rs
  native/src/widget/slider.rs
  native/src/widget/text_input.rs
  native/src/widget/toggler.rs
  native/src/widget/tooltip.rs
  style/src/application.rs
  style/src/button.rs
  style/src/checkbox.rs
  style/src/container.rs
  style/src/menu.rs
  style/src/pane_grid.rs
  style/src/pick_list.rs
  style/src/progress_bar.rs
  style/src/radio.rs
  style/src/rule.rs
  style/src/scrollable.rs
  style/src/slider.rs
  style/src/text_input.rs
  style/src/theme.rs
  style/src/toggler.rs
  winit/src/application/state.rs
Labels: feature, widget, styling

#1520 Release `0.5` — Stabilization of stateless widgets, first-class theming, widget operations, `Lazy` widget, and more!
  CHANGELOG.md
  Cargo.toml
  core/Cargo.toml
  futures/Cargo.toml
  glow/Cargo.toml
  glutin/Cargo.toml
  graphics/Cargo.toml
  lazy/Cargo.toml
  native/Cargo.toml
  style/Cargo.toml
  wgpu/Cargo.toml
  winit/Cargo.toml
Labels: bug, improvement, feature, widget, layout, rendering, shell, documentation, styling

#1521 Update iced version to 0.5
  README.md
Labels: documentation

#1533 Fixed Operations within PaneGrid
  native/src/widget/pane_grid.rs
  native/src/widget/pane_grid/content.rs
  native/src/widget/pane_grid/title_bar.rs
Labels: bug, shell

#1529 Add text input operations
  examples/todos/src/main.rs
  lazy/src/component.rs
  native/src/element.rs
  native/src/overlay/element.rs
  native/src/widget/action.rs
  native/src/widget/operation.rs
  native/src/widget/operation/text_input.rs
  native/src/widget/text_input.rs
  src/widget.rs
Labels: feature, shell

#1536 Fix mapped `Operation` always returning `Outcome::None`
  native/src/widget/action.rs
Labels: bug, shell

#1526 Add widget operation to find currently focused widget
  native/src/widget/operation/focusable.rs
  native/src/widget/scrollable.rs
  native/src/widget/text_input.rs
Labels: feature, widget, shell

#1528 #1484, #1527: Fix overlay transition
  native/src/user_interface.rs
Labels: bug, widget, shell

#1524 Additional cfg for wasm target for gradients
  glow/src/triangle.rs
  graphics/src/triangle.rs
  graphics/src/widget/canvas/frame.rs
  wgpu/src/buffer/dynamic.rs
  wgpu/src/triangle.rs
Labels: bug, rendering

#1539 Fix padding for `TextInput` with `Length::Units` width
  native/src/widget/text_input.rs
Labels: bug, widget, layout

#1560 docs: Remove invalid links.
  examples/README.md
Labels: documentation

#1538 Group all solid triangles independently of color
  Cargo.toml
  examples/README.md
  examples/geometry/Cargo.toml
  examples/geometry/README.md
  examples/geometry/src/main.rs
  glow/src/shader/common/gradient.vert
  glow/src/shader/common/solid.frag
  glow/src/shader/common/solid.vert
  glow/src/triangle.rs
  glow/src/triangle/gradient.rs
  glow/src/triangle/solid.rs
  graphics/src/layer.rs
  graphics/src/layer/mesh.rs
  graphics/src/primitive.rs
  graphics/src/triangle.rs
  graphics/src/widget/canvas.rs
  graphics/src/widget/canvas/fill.rs
  graphics/src/widget/canvas/frame.rs
  graphics/src/widget/canvas/stroke.rs
  graphics/src/widget/canvas/style.rs
  wgpu/src/buffer/dynamic.rs
  wgpu/src/buffer/static.rs
  wgpu/src/lib.rs
  wgpu/src/shader/solid.wgsl
  wgpu/src/shader/triangle.wgsl
  wgpu/src/triangle.rs
  wgpu/src/triangle/gradient.rs
  wgpu/src/triangle/solid.rs
Labels: improvement, widget, rendering, wgpu, canvas

#1557 fix: scissor layer bounds for images when using glow
  glow/src/backend.rs
  glow/src/image.rs
Labels: bug, widget, rendering, image

#1563 Allow &mut self in overlay
  lazy/src/component.rs
  lazy/src/lazy.rs
  lazy/src/responsive.rs
  native/src/element.rs
  native/src/overlay.rs
  native/src/user_interface.rs
  native/src/widget.rs
  native/src/widget/button.rs
  native/src/widget/column.rs
  native/src/widget/container.rs
  native/src/widget/pane_grid.rs
  native/src/widget/pane_grid/content.rs
  native/src/widget/pane_grid/title_bar.rs
  native/src/widget/pick_list.rs
  native/src/widget/row.rs
  native/src/widget/scrollable.rs
  native/src/widget/tooltip.rs
Labels: feature, widget

#1546 Fix overlay widget operations
  Cargo.toml
  examples/modal/Cargo.toml
  examples/modal/src/main.rs
  native/src/overlay.rs
  native/src/overlay/element.rs
  native/src/user_interface.rs
Labels: bug, widget
