Repository iced-rs/iced, pull requests merged in 2022-04, with the labels that each got.

#1301 Fix nested pure components
  lazy/src/pure/component.rs
Labels: bug, widget

#1308 fix: tree node passed in `component::OverlayInstance::on_event`
  lazy/src/pure/component.rs
Labels: bug

#1315 Implemented Tooltip as Pure
  Cargo.toml
  examples/pure/tooltip/Cargo.toml
  examples/pure/tooltip/src/main.rs
  native/src/widget/tooltip.rs
  pure/src/helpers.rs
  pure/src/widget.rs
  pure/src/widget/tooltip.rs
  src/pure/widget.rs
Labels: feature, widget

#1319 Allow use of `pure::Component` within `pure::Responsive`
  lazy/src/pure/responsive.rs
Labels: bug, widget

#1318 Fix `PickList` text wrapping
  native/src/widget/pick_list.rs
Labels: bug, widget
