Repository iced-rs/iced, pull requests merged in 2022-05, with the labels that each got.

#1328 Release `0.4` — Stateless widgets, component trait, responsive views, WebGL support, and more!
  CHANGELOG.md
  Cargo.toml
  core/Cargo.toml
  futures/Cargo.toml
  glow/Cargo.toml
  glutin/Cargo.toml
  graphics/Cargo.toml
  lazy/Cargo.toml
  native/Cargo.toml
  pure/Cargo.toml
  style/Cargo.toml
  wgpu/Cargo.toml
  winit/Cargo.toml
Labels: feature

#1330 Expose `Padding` in `iced` root crate
  src/lib.rs
Labels: bug

#1332 Fix vertical rule helper
  pure/src/helpers.rs
Labels: bug

#1333 Expose pure flex module as public
  pure/src/lib.rs
Labels: improvement, feature

#1337 Take `Borrow<dyn Widget>` instead of `Element` in `Tree` API
  pure/src/element.rs
  pure/src/widget/tree.rs
Labels: improvement, feature

#1339 Add note about resolver requirement
  README.md
Labels: documentation

#1340 Add missing versions to issue template
  .github/ISSUE_TEMPLATE/BUG-REPORT.yml
Labels: improvement

#1341 fix: prevent building component overlay with stale layout
  lazy/src/component.rs
  lazy/src/pure/component.rs
  native/src/shell.rs
  native/src/user_interface.rs
Labels: bug, layout, shell

#1353 Don't process captured overlay statuses
  native/src/user_interface.rs
Labels: bug, widget, shell

#1349 Fix `Subscription` cancelation when never awaiting
  futures/src/subscription/tracker.rs
Labels: bug, shell

#1354 Try `Limits::default` in `iced_wgpu` before `downlevel_defaults`
  wgpu/src/window/compositor.rs
Labels: bug, rendering, wgpu
