Repository iced-rs/iced, pull requests merged in 2022-01, with the labels that each got.

#1168 Change GitHub namespace to new org to prevent link-rot
  CHANGELOG.md
  Cargo.toml
  core/Cargo.toml
  core/README.md
  core/src/keyboard/event.rs
  core/src/lib.rs
  core/src/mouse/event.rs
  examples/README.md
  futures/Cargo.toml
  futures/src/lib.rs
  futures/src/subscription.rs
  glutin/Cargo.toml
  glutin/README.md
  glutin/src/lib.rs
  native/Cargo.toml
  native/README.md
  native/src/event.rs
  native/src/lib.rs
  native/src/user_interface.rs
  native/src/widget.rs
  native/src/widget/checkbox.rs
  native/src/widget/image.rs
  native/src/widget/pane_grid.rs
  native/src/widget/radio.rs
  native/src/widget/text.rs
  native/src/widget/text_input.rs
  style/Cargo.toml
  style/src/lib.rs
  web/Cargo.toml
  web/README.md
  web/src/lib.rs
  wgpu/Cargo.toml
  wgpu/README.md
  wgpu/src/backend.rs
  wgpu/src/lib.rs
  wgpu/src/widget/pane_grid.rs
Labels: improvement

#1182 Update `winit` and `glutin` forks
  glutin/Cargo.toml
  winit/Cargo.toml
Labels: improvement

#1193 `Responsive` widget
  examples/pane_grid/Cargo.toml
  examples/pane_grid/src/main.rs
  glutin/src/application.rs
  graphics/src/widget/canvas.rs
  lazy/src/cache.rs
  lazy/src/component.rs
  lazy/src/lib.rs
  lazy/src/responsive.rs
  native/src/element.rs
  native/src/lib.rs
  native/src/overlay.rs
  native/src/overlay/element.rs
  native/src/overlay/menu.rs
  native/src/program/state.rs
  native/src/shell.rs
  native/src/user_interface.rs
  native/src/widget.rs
  native/src/widget/button.rs
  native/src/widget/checkbox.rs
  native/src/widget/column.rs
  native/src/widget/container.rs
  native/src/widget/image/viewer.rs
  native/src/widget/pane_grid.rs
  native/src/widget/pane_grid/content.rs
  native/src/widget/pane_grid/title_bar.rs
  native/src/widget/pick_list.rs
  native/src/widget/radio.rs
  native/src/widget/row.rs
  native/src/widget/scrollable.rs
  native/src/widget/slider.rs
  native/src/widget/text_input.rs
  native/src/widget/toggler.rs
  native/src/widget/tooltip.rs
  winit/src/application.rs
Labels: feature

#1195 Fix `cargo-audit` vulnerabilities
  .github/workflows/audit.yml
  Cargo.toml
  core/Cargo.toml
  examples/clock/Cargo.toml
  examples/clock/src/main.rs
  examples/download_progress/Cargo.toml
  examples/pokedex/Cargo.toml
  futures/Cargo.toml
  futures/src/executor.rs
  futures/src/executor/tokio_old.rs
  futures/src/lib.rs
  futures/src/time.rs
  src/executor.rs
  src/lib.rs
Labels: bug

#1198 `websocket` example and helpers to create custom subscriptions
  Cargo.toml
  examples/clock/src/main.rs
  examples/download_progress/src/download.rs
  examples/websocket/Cargo.toml
  examples/websocket/README.md
  examples/websocket/src/echo.rs
  examples/websocket/src/echo/server.rs
  examples/websocket/src/main.rs
  native/src/subscription.rs
  native/src/subscription/events.rs
Labels: feature

#1205 Fix component overlay position
  lazy/src/component.rs
Labels: bug, layout

#1206 Invalidate widget tree in `Responsive` after a `window::Event::Resized`
  lazy/src/responsive.rs
Labels: bug, layout

#1209 Remove ambiguous `text_color` attributes for `Checkbox` and `Radio`
  examples/scrollable/src/style.rs
  examples/styling/src/main.rs
  native/src/widget/checkbox.rs
  native/src/widget/radio.rs
  style/src/checkbox.rs
  style/src/radio.rs
Labels: improvement, widget

#1213 Fix previous `overlay` affecting `cursor_position` during `draw` in `UserInterface`
  native/src/user_interface.rs
Labels: bug, layout
