Repository iced-rs/iced, pull requests merged in 2023-05, with the labels that each got.

#1822 `text::Shaping` strategy selection
  core/src/renderer/null.rs
  core/src/text.rs
  core/src/widget/text.rs
  examples/checkbox/src/main.rs
  examples/todos/src/main.rs
  graphics/src/backend.rs
  graphics/src/geometry/text.rs
  graphics/src/primitive.rs
  graphics/src/renderer.rs
  renderer/src/backend.rs
  tiny_skia/Cargo.toml
  tiny_skia/src/backend.rs
  tiny_skia/src/geometry.rs
  tiny_skia/src/text.rs
  wgpu/Cargo.toml
  wgpu/fonts/Iced-Icons.ttf
  wgpu/src/backend.rs
  wgpu/src/geometry.rs
  wgpu/src/layer.rs
  wgpu/src/layer/text.rs
  wgpu/src/text.rs
  widget/src/checkbox.rs
  widget/src/overlay/menu.rs
  widget/src/pick_list.rs
  widget/src/radio.rs
  widget/src/text.rs
  widget/src/text_input.rs
  widget/src/toggler.rs
Labels: feature, text, performance

#1828 Support configurable `LineHeight` in text widgets
  core/src/length.rs
  core/src/pixels.rs
  core/src/renderer/null.rs
  core/src/text.rs
  core/src/widget/text.rs
  graphics/src/backend.rs
  graphics/src/geometry/text.rs
  graphics/src/primitive.rs
  graphics/src/renderer.rs
  renderer/src/backend.rs
  tiny_skia/src/backend.rs
  tiny_skia/src/geometry.rs
  tiny_skia/src/text.rs
  wgpu/src/backend.rs
  wgpu/src/geometry.rs
  wgpu/src/layer.rs
  wgpu/src/layer/text.rs
  wgpu/src/text.rs
  widget/src/checkbox.rs
  widget/src/overlay/menu.rs
  widget/src/pick_list.rs
  widget/src/radio.rs
  widget/src/text_input.rs
  widget/src/toggler.rs
Labels: feature, text, widget

#1831 Fix `bounds` of selected option background in `Menu`
  native/src/overlay/menu.rs
Labels: bug, widget, styling

#1842 fix: border radius typo
  tiny_skia/src/backend.rs
Labels: bug, rendering

#1841 fix: tiny-skia svg premultiply final filtered color
  tiny_skia/src/vector.rs
Labels: bug, rendering

#1847 Fix race condition when growing an `image::Atlas`
  wgpu/src/image.rs
  wgpu/src/image/atlas.rs
  wgpu/src/image/raster.rs
  wgpu/src/image/vector.rs
Labels: bug, widget, rendering, image

#1846 [Feature] Gradients for Backgrounds
  core/Cargo.toml
  core/src/angle.rs
  core/src/background.rs
  core/src/gradient.rs
  core/src/gradient/linear.rs
  core/src/lib.rs
  core/src/renderer.rs
  examples/modern_art/Cargo.toml
  examples/modern_art/src/main.rs
  examples/solar_system/Cargo.toml
  examples/solar_system/src/main.rs
  examples/toast/src/main.rs
  examples/tour/Cargo.toml
  examples/tour/src/main.rs
  graphics/src/geometry.rs
  graphics/src/geometry/fill.rs
  graphics/src/geometry/style.rs
  graphics/src/gradient.rs
  graphics/src/lib.rs
  graphics/src/primitive.rs
  graphics/src/triangle.rs
  src/lib.rs
  style/src/button.rs
  style/src/theme.rs
  tiny_skia/src/backend.rs
  tiny_skia/src/geometry.rs
  wgpu/Cargo.toml
  wgpu/src/buffer.rs
  wgpu/src/buffer/dynamic.rs
  wgpu/src/buffer/static.rs
  wgpu/src/geometry.rs
  wgpu/src/image.rs
  wgpu/src/layer.rs
  wgpu/src/layer/mesh.rs
  wgpu/src/layer/quad.rs
  wgpu/src/lib.rs
  wgpu/src/quad.rs
  wgpu/src/shader/gradient.wgsl
  wgpu/src/shader/quad.wgsl
  wgpu/src/shader/solid.wgsl
  wgpu/src/shader/triangle.wgsl
  wgpu/src/triangle.rs
Labels: feature, rendering, styling

#1856 [Feature] Enhance PaneGrid to split panes by drag & drop
  examples/pane_grid/src/main.rs
  style/src/pane_grid.rs
  style/src/theme.rs
  widget/src/pane_grid.rs
  widget/src/pane_grid/state.rs
Labels: feature, widget

#1840 Update `glam` to `0.24`
  graphics/Cargo.toml
  wgpu/Cargo.toml
Labels: improvement

#1861 Support conversion from Fn trait to custom theme
  examples/scrollable/src/main.rs
  style/src/theme.rs
Labels: feature, styling

#1797 Make mouse::Button::Other take u16 instead of u8
  core/src/mouse/button.rs
  winit/src/conversion.rs
Labels: bug, shell

#1844 Remove min width 1 from scrollbar & scroller
  widget/src/scrollable.rs
Labels: feature, widget

#1869 Extended border radius on relevant widgets
  core/src/border_radius.rs
  core/src/lib.rs
  core/src/renderer.rs
  examples/modal/src/main.rs
  examples/scrollable/src/main.rs
  style/src/button.rs
  style/src/checkbox.rs
  style/src/container.rs
  style/src/menu.rs
  style/src/pane_grid.rs
  style/src/pick_list.rs
  style/src/progress_bar.rs
  style/src/rule.rs
  style/src/scrollable.rs
  style/src/slider.rs
  style/src/text_input.rs
  style/src/theme.rs
  widget/src/button.rs
  widget/src/checkbox.rs
  widget/src/container.rs
  widget/src/overlay/menu.rs
  widget/src/pane_grid.rs
  widget/src/pick_list.rs
  widget/src/progress_bar.rs
  widget/src/rule.rs
  widget/src/scrollable.rs
  widget/src/slider.rs
  widget/src/text_input.rs
  widget/src/vertical_slider.rs
Labels: feature, styling

#1738 Update to winit 0.28
  core/src/window.rs
  core/src/window/level.rs
  runtime/src/window.rs
  runtime/src/window/action.rs
  src/window/settings.rs
  winit/Cargo.toml
  winit/src/application.rs
  winit/src/conversion.rs
  winit/src/lib.rs
  winit/src/settings.rs
  winit/src/settings/windows.rs
Labels: improvement, feature, shell

#1875 Upgrade `palette` dependency
  core/Cargo.toml
  core/src/color.rs
  examples/checkbox/src/main.rs
  examples/color_palette/Cargo.toml
  examples/color_palette/src/main.rs
  style/Cargo.toml
  style/src/theme/palette.rs
Labels: improvement, styling

#1871 [Fix] Make gradient pack fn public for iced_graphics::Gradient
  graphics/src/gradient.rs
  graphics/src/primitive.rs
  wgpu/src/geometry.rs
  wgpu/src/layer.rs
  wgpu/src/layer/quad.rs
Labels: improvement, rendering, wgpu

#1859 Add Nix instructions to README
  DEPENDENCIES.md
Labels: developer experience, documentation

#1873 [Fix] Quads of different background types not ordered
  wgpu/src/backend.rs
  wgpu/src/layer.rs
  wgpu/src/layer/quad.rs
  wgpu/src/quad.rs
  wgpu/src/quad/gradient.rs
  wgpu/src/quad/solid.rs
Labels: bug, improvement, rendering
