Repository iced-rs/iced, pull requests merged in 2023-07, with the labels that each got.

#1927 Add command to retrieve window size
  runtime/src/window.rs
  runtime/src/window/action.rs
  winit/src/application.rs
Labels: feature, shell

#1865 [Feature] Pane Grid: drag & drop panes to the edges
  examples/pane_grid/src/main.rs
  style/src/pane_grid.rs
  widget/src/pane_grid.rs
  widget/src/pane_grid/node.rs
  widget/src/pane_grid/state.rs
Labels: feature, widget

#1949 Forward redraw requests in component overlay
  widget/src/lazy/component.rs
Labels: bug, shell

#1692 Use overlay for tooltip
  widget/src/tooltip.rs
Labels: feature, widget, rendering

#1907 Update `resvg` to `0.35` and `tiny-skia` to `0.10`
  tiny_skia/Cargo.toml
  tiny_skia/src/backend.rs
  tiny_skia/src/raster.rs
  tiny_skia/src/text.rs
  tiny_skia/src/vector.rs
  wgpu/Cargo.toml
  wgpu/src/image/vector.rs
Labels: improvement, widget, rendering, svg

#1912 Add scrollable alignment option
  examples/scrollable/src/main.rs
  widget/src/scrollable.rs
Labels: feature, widget, layout

#1955 Dont blink input cursor when window loses focus
  widget/src/text_input.rs
Labels: bug, animation, widget, rendering

#1961 Update `cosmic-text` and `glyphon`
  tiny_skia/Cargo.toml
  wgpu/Cargo.toml
  wgpu/src/backend.rs
  wgpu/src/text.rs
Labels: improvement, text, rendering

#1960 Update `CHANGELOG`
  CHANGELOG.md
  docs/release_summary.py
Labels: improvement, documentation

#1966 Don't clip raw overlay bounds
  runtime/src/user_interface.rs
Labels: bug, rendering

#1970 Add workflow to verify `CHANGELOG` is always up-to-date
  .github/workflows/verify.yml
  CHANGELOG.md
Labels: improvement, documentation

#1963 Add app id setting for linux
  CHANGELOG.md
  winit/src/settings.rs
  winit/src/settings/linux.rs
Labels: feature, shell

#1958 minor doc updates
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  ROADMAP.md
Labels: improvement, documentation

#1954 Add `ComboBox` widget
  CHANGELOG.md
  examples/combo_box/Cargo.toml
  examples/combo_box/README.md
  examples/combo_box/combobox.gif
  examples/combo_box/src/main.rs
  widget/src/combo_box.rs
  widget/src/helpers.rs
  widget/src/lib.rs
  widget/src/overlay/menu.rs
  widget/src/pick_list.rs
  widget/src/text_input.rs
Labels: feature, widget

#1971 `visible_bounds` operation for `Container`
  CHANGELOG.md
  core/src/element.rs
  core/src/overlay/element.rs
  core/src/overlay/group.rs
  core/src/rectangle.rs
  core/src/widget/operation.rs
  core/src/widget/operation/focusable.rs
  core/src/widget/operation/scrollable.rs
  core/src/widget/operation/text_input.rs
  examples/toast/src/main.rs
  examples/visible_bounds/Cargo.toml
  examples/visible_bounds/src/main.rs
  widget/src/button.rs
  widget/src/column.rs
  widget/src/container.rs
  widget/src/lazy/component.rs
  widget/src/pane_grid.rs
  widget/src/row.rs
  widget/src/scrollable.rs
Labels: widget, layout

#1972 add border radius to public API
  CHANGELOG.md
  src/lib.rs
Labels: improvement

#1978 Fix `Tooltip` overlay position inside `Scrollable`
  CHANGELOG.md
  widget/src/tooltip.rs
Labels: bug, widget
