Repository iced-rs/iced, pull requests merged in 2023-03, with the labels that each got.

#1742 [Fix] Fullscreen only works on primary monitor
  examples/todos/src/main.rs
  src/window.rs
  winit/src/application.rs
Labels: bug, shell

#1750 Use correct package name in checkbox example docs
  examples/checkbox/README.md
Labels: documentation

#1755 Fix `clippy` lints for Rust 1.68
  core/src/font.rs
  core/src/mouse/interaction.rs
  examples/pick_list/src/main.rs
  examples/todos/src/main.rs
  graphics/src/primitive.rs
  graphics/src/widget/canvas/cache.rs
  graphics/src/widget/canvas/stroke.rs
Labels: improvement

#1730 Platform specific `window` options.
  src/window.rs
  src/window/settings.rs
Labels: feature, shell

#1765 winit: Fix replacement of node in wasm
  winit/src/application.rs
Labels: bug, shell, web

#1754 [Optimization] Reduce unnecessary `Component` rebuilds
  lazy/src/component.rs
Labels: improvement, performance, widget

#1669 Added scrollable style `focused` to be displayed when mouse is over the scrollable area
  examples/scrollable/src/main.rs
  native/src/widget/scrollable.rs
  style/src/scrollable.rs
  style/src/theme.rs
Labels: feature, widget, styling
