Repository iced-rs/iced, pull requests merged in 2023-11, with the labels that each got.

#2080 Migrate twox-hash -> xxhash-rust. Switch to Xxh3 for better performance.
  Cargo.toml
  core/Cargo.toml
  core/src/hasher.rs
  graphics/Cargo.toml
  graphics/src/text/cache.rs
  tiny_skia/Cargo.toml
Labels: improvement, performance, web, change

#1908 Run convert_text on svg trees so text renders correctly
  Cargo.toml
  tiny_skia/src/vector.rs
Labels: bug, rendering, svg, fix

#1894 Add texture filtering options
  core/src/image.rs
  examples/tour/src/main.rs
  graphics/src/primitive.rs
  graphics/src/renderer.rs
  renderer/src/lib.rs
  tiny_skia/src/backend.rs
  tiny_skia/src/raster.rs
  wgpu/src/image.rs
  wgpu/src/layer.rs
  wgpu/src/layer/image.rs
  widget/src/image.rs
  widget/src/image/viewer.rs
Labels: feature, rendering, image, addition

#2134 Fix standalone compilation of `iced_renderer` crate
  .github/workflows/check.yml
  .github/workflows/test.yml
  renderer/src/lib.rs
Labels: bug, fix

#2135 Deny warnings in `test` workflow
  .github/workflows/test.yml
  examples/lazy/src/main.rs
  examples/modal/src/main.rs
  examples/toast/src/main.rs
  highlighter/src/lib.rs
Labels: improvement

#2085 [Feature] Custom Shader Widget
  Cargo.toml
  examples/custom_shader/Cargo.toml
  examples/custom_shader/src/main.rs
  examples/custom_shader/src/scene.rs
  examples/custom_shader/src/scene/camera.rs
  examples/custom_shader/src/scene/pipeline.rs
  examples/custom_shader/src/scene/pipeline/buffer.rs
  examples/custom_shader/src/scene/pipeline/cube.rs
  examples/custom_shader/src/scene/pipeline/uniforms.rs
  examples/custom_shader/src/scene/pipeline/vertex.rs
  examples/custom_shader/src/shaders/cubes.wgsl
  examples/custom_shader/src/shaders/depth.wgsl
  examples/custom_shader/textures/ice_cube_normal_map.png
  examples/custom_shader/textures/skybox/neg_x.jpg
  examples/custom_shader/textures/skybox/neg_y.jpg
  examples/custom_shader/textures/skybox/neg_z.jpg
  examples/custom_shader/textures/skybox/pos_x.jpg
  examples/custom_shader/textures/skybox/pos_y.jpg
  examples/custom_shader/textures/skybox/pos_z.jpg
  examples/integration/src/main.rs
  graphics/Cargo.toml
  renderer/src/lib.rs
  renderer/src/widget.rs
  wgpu/src/backend.rs
  wgpu/src/layer.rs
  wgpu/src/primitive.rs
  wgpu/src/primitive/pipeline.rs
  wgpu/src/window/compositor.rs
  widget/Cargo.toml
  widget/src/helpers.rs
  widget/src/lib.rs
  widget/src/shader.rs
  widget/src/shader/event.rs
  widget/src/shader/program.rs
Labels: feature, widget, rendering, wgpu, addition

#2142 Fix `Overlay` composition
  core/src/overlay.rs
  core/src/overlay/element.rs
  core/src/overlay/group.rs
  examples/modal/src/main.rs
  examples/toast/src/main.rs
  runtime/src/overlay/nested.rs
  runtime/src/user_interface.rs
  widget/src/lazy.rs
  widget/src/lazy/component.rs
  widget/src/lazy/responsive.rs
  widget/src/overlay/menu.rs
  widget/src/tooltip.rs
Labels: bug, layout, fix

#2141 Use the correct GIF for the progress bar example
  examples/progress_bar/README.md
Labels: documentation, fix

#2143 Invalidate layout when `Tooltip` changes `overlay`
  widget/src/tooltip.rs
Labels: bug, layout, fix

#2149 Provide actual bounds to `Shader` primitives
  examples/custom_shader/src/main.rs
  examples/custom_shader/src/scene.rs
  examples/custom_shader/src/scene/pipeline.rs
  wgpu/src/backend.rs
  wgpu/src/layer.rs
  wgpu/src/layer/pipeline.rs
  wgpu/src/primitive/pipeline.rs
  widget/src/shader.rs
Labels: widget, rendering, change

#2150 `Stream` support for `Command`
  futures/src/runtime.rs
  runtime/src/command.rs
  runtime/src/command/action.rs
  src/lib.rs
  winit/src/application.rs
Labels: feature
