Repository iced-rs/iced, pull requests merged in 2023-01, with the labels that each got.

#1616 Use same name & order for toggler::new and helper
  native/src/widget/helpers.rs
  native/src/widget/toggler.rs
Labels: improvement, feature, widget

#1624 Minor docs typo
  graphics/src/image/storage.rs
Labels: improvement, documentation

#1628 Add `operate` method to `Component` trait
  lazy/src/component.rs
Labels: feature, widget

#1622 TextInput: SHIFT+Left Click to Select
  native/src/widget/text_input.rs
Labels: feature, widget

#1584 add action to request user attention
  native/src/window.rs
  native/src/window/action.rs
  native/src/window/user_attention.rs
  winit/src/application.rs
  winit/src/conversion.rs
  winit/src/window.rs
Labels: feature, shell

#1562 Added ability to customize the handle of a `pick_list`
  native/src/widget/pick_list.rs
  src/widget.rs
  style/src/pick_list.rs
  style/src/theme.rs
Labels: feature, widget, styling

#1585 add action to make window focus
  native/src/window/action.rs
  winit/src/application.rs
Labels: feature, shell

#1634 fix doc links
  src/lib.rs
Labels: documentation

#1635 Make count fields pub
  native/src/widget/operation/focusable.rs
Labels: feature

#1636 Make location copy
  graphics/src/gradient.rs
Labels: feature

#1639 Stop using `f32::clamp` altogether in `layout::Limits`
  native/src/layout/limits.rs
Labels: bug, layout

#1550 [Feature] Multidirectional scrolling
  core/src/size.rs
  examples/README.md
  examples/scrollable/Cargo.toml
  examples/scrollable/screenshot.png
  examples/scrollable/src/main.rs
  examples/websocket/src/main.rs
  native/src/widget/column.rs
  native/src/widget/operation/scrollable.rs
  native/src/widget/scrollable.rs
  src/widget.rs
  style/src/scrollable.rs
  style/src/theme.rs
Labels: feature, widget

#1644 Fix `overlay` implementation for `Lazy` widget
  examples/cached/Cargo.toml
  examples/cached/src/main.rs
  examples/lazy/src/main.rs
  lazy/src/lazy.rs
Labels: bug, widget

#1646 Provide `&Dependency` to `Lazy` widget view fn
  examples/lazy/src/main.rs
  lazy/src/lazy.rs
  lazy/src/lib.rs
Labels: feature, widget

#1648 Fix comment description on crate example
  src/lib.rs
Labels: improvement, documentation

#1647 Widget-driven animations
  core/Cargo.toml
  core/src/time.rs
  examples/events/Cargo.toml
  examples/events/src/main.rs
  examples/exit/src/main.rs
  examples/solar_system/src/main.rs
  glutin/Cargo.toml
  glutin/src/application.rs
  native/src/renderer.rs
  native/src/shell.rs
  native/src/subscription.rs
  native/src/user_interface.rs
  native/src/widget/text_input.rs
  native/src/window.rs
  native/src/window/event.rs
  native/src/window/redraw_request.rs
  src/application.rs
  src/sandbox.rs
  winit/src/application.rs
  winit/src/window.rs
Labels: animation, widget, rendering, shell

#1649 Introduce `custom` method to `widget::Operation` trait
  native/src/element.rs
  native/src/overlay/element.rs
  native/src/widget/action.rs
  native/src/widget/operation.rs
Labels: feature, widget

#1660 Update example/game_of_life: use [default] on enum
  examples/game_of_life/src/preset.rs
Labels: improvement

#1655 Group Overlay
  examples/toast/Cargo.toml
  examples/toast/src/main.rs
  native/src/overlay.rs
  native/src/overlay/element.rs
  native/src/overlay/group.rs
  native/src/shell.rs
  native/src/user_interface.rs
  native/src/widget/pane_grid.rs
Labels: feature, widget, rendering

#1676 Annotate `Command` and `Subscription` with `#[must_use]`
  futures/src/command.rs
  futures/src/subscription.rs
  native/src/command.rs
Labels: improvement

#1681 Fix Clippy Lints
  examples/download_progress/src/main.rs
  examples/events/src/main.rs
  examples/game_of_life/src/main.rs
  examples/integration_opengl/src/controls.rs
  examples/integration_opengl/src/scene.rs
  examples/integration_wgpu/src/controls.rs
  examples/integration_wgpu/src/main.rs
  examples/pokedex/src/main.rs
  examples/styling/src/main.rs
  examples/system_information/src/main.rs
  examples/todos/src/main.rs
  examples/tour/src/main.rs
  examples/websocket/src/echo.rs
  examples/websocket/src/echo/server.rs
  futures/src/backend/native/async_std.rs
  futures/src/backend/native/tokio.rs
  glow/src/program.rs
  graphics/src/renderer.rs
  native/src/command/action.rs
  native/src/debug/basic.rs
  native/src/image.rs
  native/src/renderer.rs
  native/src/svg.rs
  native/src/widget/operation.rs
  native/src/window/action.rs
  src/window/icon.rs
  wgpu/src/settings.rs
  winit/src/application.rs
  winit/src/application/profiler.rs
Labels: improvement

#1679 Fixed a 1-pixel width issue on `pick_list`
  native/src/overlay/menu.rs
Labels: bug, widget, rendering

#1678 Mapped operations is missing text_input()
  native/src/widget/action.rs
Labels: bug, widget

#1682 Refactor image draw to standalone function
  native/src/widget/image.rs
Labels: improvement, widget, rendering, image

#1685 Fix widget-driven animations for `Component`
  lazy/src/component.rs
Labels: bug, animation, widget, rendering, shell

#1686 Fix layout translation in `overlay::Group`
  core/src/vector.rs
  lazy/src/component.rs
  lazy/src/lazy.rs
  lazy/src/responsive.rs
  native/src/overlay/element.rs
  native/src/overlay/group.rs
  native/src/user_interface.rs
Labels: bug, widget, layout
