Repository iced-rs/iced, pull requests merged in 2023-02, with the labels that each got.

#1694 Accept FnOnce instead of Fn in canvas cache draw
  graphics/src/widget/canvas/cache.rs
Labels: feature, widget, canvas

#1659 Resize images on README.md
  README.md
Labels: improvement, documentation

#1699 Implement `is_over` for iced_lazy widget `Overlay`s
  lazy/src/component.rs
  lazy/src/lazy.rs
  lazy/src/responsive.rs
Labels: bug, widget

#1700 Fix panic when overlay event processing removes overlay
  native/src/user_interface.rs
Labels: bug, widget

#1698 Hide window until `Renderer` has been initialized
  winit/src/application.rs
  winit/src/settings.rs
Labels: improvement, rendering, shell

#1701 Fix panic when using operations with components in certain cases
  lazy/src/component.rs
Labels: bug, widget

#1675 Extended `pick_list::Handle` to be more flexible
  native/src/widget/pick_list.rs
  src/widget.rs
Labels: feature, widget, styling

#1706 Pad after setting width in text input
  native/src/widget/text_input.rs
Labels: bug, widget, layout

#1695 Provide widgets IDs to `Operation::container`
  native/src/widget/container.rs
  native/src/widget/scrollable.rs
Labels: bug, feature, widget

#1707 Added the ability to change `Checkbox` icon
  examples/checkbox/Cargo.toml
  examples/checkbox/README.md
  examples/checkbox/fonts/icons.ttf
  examples/checkbox/src/main.rs
  native/src/widget/checkbox.rs
  src/widget.rs
  style/src/checkbox.rs
  style/src/theme.rs
Labels: feature, widget, styling

#1587 add always on top action
  native/src/window/action.rs
  winit/src/application.rs
  winit/src/window.rs
Labels: feature, shell

#1589 add action to get window id
  native/src/window/action.rs
  winit/src/application.rs
  winit/src/window.rs
Labels: feature, shell

#1665 Minor update: `example/qr_code`
  examples/qr_code/src/main.rs
Labels: improvement

#1551 image: Allow any kind of data that implements `AsRef<[u8]>` for the i…
  examples/pokedex/src/main.rs
  native/src/image.rs
Labels: feature, performance, image

#1711 Generic pixel units
  core/src/length.rs
  core/src/lib.rs
  core/src/padding.rs
  core/src/pixels.rs
  core/src/size.rs
  examples/color_palette/src/main.rs
  examples/component/src/main.rs
  examples/events/src/main.rs
  examples/integration_opengl/src/controls.rs
  examples/integration_wgpu/src/controls.rs
  examples/modal/src/main.rs
  examples/pick_list/src/main.rs
  examples/qr_code/src/main.rs
  examples/scrollable/src/main.rs
  examples/slider/src/main.rs
  examples/stopwatch/src/main.rs
  examples/styling/src/main.rs
  examples/todos/src/main.rs
  examples/tour/src/main.rs
  glow/src/backend.rs
  glow/src/settings.rs
  graphics/src/backend.rs
  graphics/src/renderer.rs
  graphics/src/widget/canvas.rs
  lazy/src/responsive.rs
  native/src/layout/flex.rs
  native/src/layout/limits.rs
  native/src/lib.rs
  native/src/overlay/menu.rs
  native/src/renderer/null.rs
  native/src/text.rs
  native/src/widget/button.rs
  native/src/widget/checkbox.rs
  native/src/widget/column.rs
  native/src/widget/container.rs
  native/src/widget/helpers.rs
  native/src/widget/image.rs
  native/src/widget/image/viewer.rs
  native/src/widget/pane_grid.rs
  native/src/widget/pane_grid/title_bar.rs
  native/src/widget/pick_list.rs
  native/src/widget/progress_bar.rs
  native/src/widget/radio.rs
  native/src/widget/row.rs
  native/src/widget/rule.rs
  native/src/widget/scrollable.rs
  native/src/widget/slider.rs
  native/src/widget/space.rs
  native/src/widget/svg.rs
  native/src/widget/text.rs
  native/src/widget/text_input.rs
  native/src/widget/toggler.rs
  native/src/widget/tooltip.rs
  native/src/widget/vertical_slider.rs
  src/settings.rs
  wgpu/src/backend.rs
  wgpu/src/settings.rs
Labels: improvement, feature, layout

#1714 Fix height of `overlay::Menu`
  native/src/overlay/menu.rs
Labels: bug, widget, layout

#1716 Fix base cursor position during `UserInterface::draw` when overlay is present
  native/src/user_interface.rs
Labels: bug, widget

#1717 Remove `Clone` bound for `Bytes::new` in `image`
  native/src/image.rs
Labels: improvement, widget, image

#1721 Sliders no longer bleed over rail
  native/src/widget/slider.rs
  native/src/widget/vertical_slider.rs
Labels: improvement, widget

#1723 Change `subscription::run` to take a function pointer
  native/src/subscription.rs
Labels: feature

#1731 Remove logging large bytes arrays
  glow/src/settings.rs
  glutin/src/application.rs
  src/window/icon.rs
  wgpu/src/settings.rs
  winit/src/application.rs
  winit/src/settings.rs
Labels: improvement, developer experience

#1733 Update `resvg` in `iced_graphics`
  graphics/Cargo.toml
  graphics/src/image/vector.rs
Labels: improvement, rendering

#1734 Fix `Padding::fit` on irregular values for an axis
  core/src/padding.rs
Labels: bug, layout

#1735 Remove `Fill` variant for `Alignment`
  core/src/alignment.rs
  examples/component/src/main.rs
  examples/scrollable/src/main.rs
  examples/websocket/src/main.rs
  native/src/layout/flex.rs
  native/src/layout/node.rs
Labels: feature, layout
