Repository iced-rs/iced, pull requests merged in 2023-09, with the labels that each got.

#2065 Update `wgpu` to `0.17`
  CHANGELOG.md
  examples/integration/src/main.rs
  wgpu/Cargo.toml
Labels: improvement, wgpu

#2067 Introduce `theme::Custom::with_fn` to generate completely custom themes
  CHANGELOG.md
  style/src/theme.rs
Labels: feature, styling

#2062 fix(examples-styling): fixed checkbox and toggler getting hidden behind scrollbar
  CHANGELOG.md
  examples/styling/src/main.rs
Labels: bug, improvement, fix

#2046 Support automatic style type casting for Buttons.
  CHANGELOG.md
  widget/src/button.rs
Labels: improvement, styling, change

#2068 Enable WebGPU backend in `wgpu` by default instead of WebGL
  .github/workflows/test.yml
  Cargo.toml
  renderer/Cargo.toml
  wgpu/Cargo.toml
Labels: feature, rendering, wgpu, change

#2073 Add `keyboard` subscriptions and rename `subscription::events` to `event::listen`
  examples/events/src/main.rs
  examples/modal/src/main.rs
  examples/pane_grid/src/main.rs
  examples/screenshot/src/main.rs
  examples/stopwatch/src/main.rs
  examples/toast/src/main.rs
  examples/todos/src/main.rs
  examples/url_handler/src/main.rs
  examples/visible_bounds/src/main.rs
  futures/src/event.rs
  futures/src/keyboard.rs
  futures/src/lib.rs
  futures/src/subscription.rs
  runtime/src/window.rs
  src/lib.rs
Labels: improvement, subscription, change

#2059 [issue #2002] Ensure that absolute `LineHeight` is always > 0.0
  tiny_skia/src/text.rs
  wgpu/src/text.rs
Labels: text, rendering, fix

#2072 Add access to bounds/content bounds from a scrollable viewport.
  widget/src/scrollable.rs
Labels: widget, addition

#2074 Host GIFs and video examples in `iced.rs`
  README.md
  examples/README.md
  examples/bezier_tool/README.md
  examples/color_palette/README.md
  examples/counter/README.md
  examples/custom_widget/README.md
  examples/download_progress/README.md
  examples/events/README.md
  examples/game_of_life/README.md
  examples/geometry/README.md
  examples/integration/README.md
  examples/loading_spinners/README.md
  examples/pane_grid/README.md
  examples/pokedex/README.md
  examples/progress_bar/README.md
  examples/qr_code/README.md
  examples/sierpinski_triangle/README.md
  examples/solar_system/README.md
  examples/stopwatch/README.md
  examples/styling/README.md
  examples/todos/README.md
  examples/tour/README.md
  src/lib.rs
  widget/src/pane_grid.rs
Labels: documentation, fix

#2071 use @interpolate(flat) attribute as per the WebGPU spec
  wgpu/src/shader/quad.wgsl
  wgpu/src/shader/triangle.wgsl
Labels: bug, rendering, wgpu, fix

#2070 Added a Frame::scale_nonuniform method
  examples/game_of_life/src/main.rs
  renderer/src/geometry.rs
  tiny_skia/src/geometry.rs
  wgpu/src/geometry.rs
  widget/src/qr_code.rs
Labels: feature, rendering, canvas, addition

#2055 Compute gradients in Oklab color space
  clippy.toml
  core/Cargo.toml
  core/src/angle.rs
  examples/gradient/Cargo.toml
  examples/gradient/src/main.rs
  wgpu/src/quad/gradient.rs
  wgpu/src/quad/solid.rs
  wgpu/src/shader/color/linear_rgb.wgsl
  wgpu/src/shader/color/oklab.wgsl
  wgpu/src/shader/quad.wgsl
  wgpu/src/shader/quad/gradient.wgsl
  wgpu/src/shader/quad/solid.wgsl
  wgpu/src/shader/triangle.wgsl
  wgpu/src/shader/triangle/gradient.wgsl
  wgpu/src/shader/triangle/solid.wgsl
  wgpu/src/triangle.rs
  widget/src/slider.rs
Labels: feature, rendering, addition

#2077 Fix majority of unresolved documentation links
  .github/workflows/document.yml
  core/src/angle.rs
  core/src/gradient.rs
  core/src/lib.rs
  core/src/shell.rs
  core/src/window/icon.rs
  futures/src/lib.rs
  futures/src/runtime.rs
  futures/src/subscription.rs
  futures/src/subscription/tracker.rs
  graphics/src/compositor.rs
  graphics/src/geometry.rs
  graphics/src/geometry/fill.rs
  graphics/src/geometry/stroke.rs
  graphics/src/gradient.rs
  graphics/src/lib.rs
  graphics/src/mesh.rs
  renderer/src/geometry.rs
  renderer/src/lib.rs
  renderer/src/settings.rs
  runtime/src/lib.rs
  runtime/src/overlay/nested.rs
  runtime/src/program/state.rs
  runtime/src/user_interface.rs
  src/lib.rs
  src/settings.rs
  src/window/icon.rs
  style/src/lib.rs
  tiny_skia/src/geometry.rs
  tiny_skia/src/lib.rs
  tiny_skia/src/raster.rs
  tiny_skia/src/text.rs
  tiny_skia/src/vector.rs
  tiny_skia/src/window/compositor.rs
  wgpu/src/geometry.rs
  wgpu/src/lib.rs
  widget/src/canvas/event.rs
  widget/src/canvas/program.rs
  widget/src/checkbox.rs
  widget/src/combo_box.rs
  widget/src/helpers.rs
  widget/src/lib.rs
  widget/src/overlay/menu.rs
  widget/src/pane_grid/configuration.rs
  widget/src/pane_grid/content.rs
  widget/src/pane_grid/node.rs
  widget/src/pane_grid/pane.rs
  widget/src/pane_grid/split.rs
  widget/src/pane_grid/state.rs
  widget/src/pane_grid/title_bar.rs
  widget/src/pick_list.rs
  widget/src/radio.rs
  widget/src/text_input.rs
  widget/src/text_input/value.rs
  widget/src/toggler.rs
  winit/src/application/state.rs
  winit/src/conversion.rs
  winit/src/lib.rs
Labels: documentation, fix

#2076 Get web examples running again
  examples/counter/Cargo.toml
  examples/counter/README.md
  examples/integration/Cargo.toml
  examples/integration/src/main.rs
  examples/todos/Cargo.toml
  examples/todos/README.md
  examples/tour/Cargo.toml
  examples/tour/src/main.rs
Labels: web, fix

#2078 Fix `ComboBox` widget panic on wasm
  widget/src/combo_box.rs
Labels: widget, web, fix

#2084 Fix width of horizontal scrollbar in `Scrollable`
  examples/scrollable/src/main.rs
  widget/src/scrollable.rs
Labels: widget, layout, fix

#2089 Chore: Inline format args for ease of reading
  examples/game_of_life/src/main.rs
  examples/screenshot/src/main.rs
  examples/system_information/src/main.rs
  examples/todos/src/main.rs
  examples/visible_bounds/src/main.rs
  futures/src/subscription/tracker.rs
  renderer/src/lib.rs
  tiny_skia/src/backend.rs
  wgpu/src/image/atlas.rs
  wgpu/src/image/vector.rs
  wgpu/src/window/compositor.rs
  winit/src/application.rs
  winit/src/clipboard.rs
Labels: improvement, fix

#2090 Chore: Apply clippy map transformations
  core/src/mouse/click.rs
  examples/integration/src/main.rs
  examples/screenshot/src/main.rs
  wgpu/src/image/vector.rs
  wgpu/src/triangle.rs
  winit/src/application/state.rs
  winit/src/clipboard.rs
Labels: improvement, fix

#2091 Chore: Apply clippy docs keyword quoting
  core/src/color.rs
  core/src/window/icon.rs
  futures/src/subscription.rs
  graphics/src/compositor.rs
  runtime/src/window/screenshot.rs
  style/src/rule.rs
Labels: improvement, documentation, fix

#2092 Chore: Apply some minor clippy fixes
  core/src/gradient.rs
  core/src/widget/text.rs
  examples/game_of_life/src/main.rs
  examples/tour/src/main.rs
  graphics/src/gradient.rs
  runtime/src/debug/basic.rs
  tiny_skia/src/geometry.rs
Labels: improvement, fix
