Repository iced-rs/iced, pull requests merged in 2024-10, with the labels that each got.

#2617 fix: circular progress no longer skips
  examples/loading_spinners/src/circular.rs
Labels: improvement, documentation, fix

#2615 Document Wayland `File*` Events as Unsupported & Fix Typos
  core/src/keyboard/key.rs
  core/src/keyboard/modifiers.rs
  core/src/text.rs
  core/src/window/event.rs
  graphics/src/compositor.rs
  runtime/src/system.rs
  runtime/src/window.rs
  widget/src/button.rs
  widget/src/checkbox.rs
  widget/src/combo_box.rs
  widget/src/markdown.rs
  widget/src/text/rich.rs
Labels: improvement, shell, documentation, fix

#2619 Derive `Default` for `iced_wgpu::geometry::Cache`
  wgpu/src/geometry.rs
Labels: feature, wgpu, addition

#2608 added physical_key to KeyReleased event
  core/src/keyboard/event.rs
  winit/src/conversion.rs
Labels: feature, shell, addition

#2611 Don't fill out of viewport text
  widget/src/column.rs
  widget/src/row.rs
Labels: improvement, performance, widget

#2623 Change lifetime of markdown IntoIterator Item, as it does not need to live as long as the returned Element
  widget/src/markdown.rs
Labels: improvement, widget

#2637 Add PartialEq derives for widget styles
  core/src/widget/text.rs
  widget/src/checkbox.rs
  widget/src/container.rs
  widget/src/overlay/menu.rs
  widget/src/pick_list.rs
  widget/src/progress_bar.rs
  widget/src/radio.rs
  widget/src/rule.rs
  widget/src/scrollable.rs
  widget/src/slider.rs
  widget/src/text_editor.rs
  widget/src/text_input.rs
  widget/src/toggler.rs
Labels: feature, styling, addition

#2632 Fixed bug where delete key wasn't working in the text editor
  widget/src/text_editor.rs
Labels: bug, text, widget, fix

#2639 Introduce consecutive click distance check like other toolkit do such as gtk,qt, imgui.
  core/src/mouse/click.rs
Labels: bug, widget, fix

#2649 Prevent unintended keyboard input during focus.
  winit/src/conversion.rs
Labels: bug, shell, fix

#2651 Use float total_cmp instead of partial_cmp to get a total order.
  graphics/src/damage.rs
Labels: bug, rendering, fix
