Repository iced-rs/iced, pull requests merged in 2024-12, with the labels that each got.

#2683 Call `OnPress::get` only when button is pressed
  widget/src/button.rs
Labels: bug, widget, fix

#2681 fix: add an initial state to the `system_information` example
  examples/system_information/src/main.rs
Labels: improvement, fix

#2675 Request redraw in tooltip widget when cursor is hovering
  widget/src/tooltip.rs
Labels: bug, rendering, fix

#2691 Emit pane_grid::DragEvent::Canceled within deadband
  widget/src/pane_grid.rs
Labels: bug, widget, fix

#2698 Headless Mode Testing
  .github/workflows/test.yml
  .gitignore
  Cargo.lock
  Cargo.toml
  core/src/keyboard/key.rs
  core/src/lib.rs
  core/src/renderer.rs
  core/src/settings.rs
  core/src/theme.rs
  core/src/widget/operation.rs
  core/src/widget/operation/focusable.rs
  core/src/widget/operation/scrollable.rs
  core/src/widget/operation/text_input.rs
  core/src/widget/text.rs
  core/src/window.rs
  core/src/window/screenshot.rs
  core/src/window/settings.rs
  examples/counter/Cargo.toml
  examples/counter/src/main.rs
  examples/gradient/src/main.rs
  examples/todos/Cargo.toml
  examples/todos/snapshots/creates_a_new_task.sha256
  examples/todos/src/main.rs
  examples/tour/Cargo.toml
  graphics/src/text.rs
  renderer/src/lib.rs
  runtime/src/window.rs
  src/application.rs
  src/daemon.rs
  src/lib.rs
  src/program.rs
  test/Cargo.toml
  test/src/lib.rs
  test/src/selector.rs
  tiny_skia/src/lib.rs
  widget/src/checkbox.rs
  widget/src/container.rs
  widget/src/scrollable.rs
  widget/src/text_editor.rs
  widget/src/text_input.rs
  winit/src/program.rs
  winit/src/program/state.rs
  winit/src/program/window_manager.rs
  winit/src/settings.rs
Labels: feature, developer experience, shell, addition
