Repository iced-rs/iced, pull requests merged in 2024-06, with the labels that each got.

#2456 Introduce `window::Id` to `Event` subscriptions
  core/src/event.rs
  examples/events/src/main.rs
  examples/integration/src/main.rs
  examples/loading_spinners/src/circular.rs
  examples/loading_spinners/src/linear.rs
  examples/multi_window/src/main.rs
  examples/toast/src/main.rs
  examples/url_handler/src/main.rs
  examples/visible_bounds/src/main.rs
  futures/src/event.rs
  futures/src/keyboard.rs
  futures/src/runtime.rs
  futures/src/subscription.rs
  futures/src/subscription/tracker.rs
  runtime/src/window.rs
  src/lib.rs
  wgpu/src/quad/gradient.rs
  wgpu/src/quad/solid.rs
  widget/src/canvas.rs
  widget/src/lazy/cache.rs
  widget/src/shader.rs
  widget/src/text_input.rs
  winit/src/application.rs
  winit/src/conversion.rs
  winit/src/multi_window.rs
Labels: feature, shell, subscription, addition

#2465 Fix DEPENDENCIES.md for wayland
  DEPENDENCIES.md
Labels: developer experience, documentation, fix

#2460 Add FromIterator for Row and Column
  widget/src/column.rs
  widget/src/row.rs
Labels: feature, developer experience, widget, addition

#2330 Implement content_fit for viewer widget
  widget/src/image/viewer.rs
Labels: feature, widget, layout, rendering, image, addition

#2469 `Daemon` API and Shell Runtime Unification
  Cargo.toml
  core/src/window/id.rs
  examples/arc/src/main.rs
  examples/bezier_tool/src/main.rs
  examples/checkbox/src/main.rs
  examples/clock/src/main.rs
  examples/color_palette/src/main.rs
  examples/custom_shader/src/main.rs
  examples/download_progress/src/main.rs
  examples/editor/src/main.rs
  examples/events/src/main.rs
  examples/exit/src/main.rs
  examples/ferris/src/main.rs
  examples/game_of_life/src/main.rs
  examples/gradient/src/main.rs
  examples/layout/src/main.rs
  examples/loading_spinners/src/main.rs
  examples/modal/src/main.rs
  examples/multi_window/src/main.rs
  examples/multitouch/src/main.rs
  examples/pane_grid/src/main.rs
  examples/pokedex/src/main.rs
  examples/qr_code/src/main.rs
  examples/screenshot/src/main.rs
  examples/scrollable/src/main.rs
  examples/sierpinski_triangle/src/main.rs
  examples/solar_system/src/main.rs
  examples/stopwatch/src/main.rs
  examples/styling/src/main.rs
  examples/system_information/src/main.rs
  examples/the_matrix/src/main.rs
  examples/toast/src/main.rs
  examples/todos/src/main.rs
  examples/tour/src/main.rs
  examples/url_handler/src/main.rs
  examples/vectorial_text/src/main.rs
  examples/visible_bounds/src/main.rs
  examples/websocket/src/main.rs
  runtime/src/lib.rs
  runtime/src/task.rs
  runtime/src/window.rs
  src/advanced.rs
  src/application.rs
  src/daemon.rs
  src/lib.rs
  src/multi_window.rs
  src/program.rs
  src/settings.rs
  winit/Cargo.toml
  winit/src/application.rs
  winit/src/lib.rs
  winit/src/multi_window/state.rs
  winit/src/program.rs
  winit/src/program/state.rs
  winit/src/program/window_manager.rs
  winit/src/proxy.rs
  winit/src/settings.rs
Labels: feature, shell, change, addition

#2470 feat: Add methods for window settings in Application
  src/application.rs
Labels: feature, shell, addition

#2475 Implement Copy on Fill and Stroke
  graphics/src/geometry/fill.rs
  graphics/src/geometry/stroke.rs
  graphics/src/geometry/style.rs
  graphics/src/gradient.rs
Labels: feature, canvas, addition

#2487 doc: fix "Reconciles" typo
  core/src/widget.rs
  core/src/widget/tree.rs
Labels: documentation, fix

#2485 doc: clarify Quad border alignment
  core/src/renderer.rs
Labels: documentation, addition
