Repository iced-rs/iced, pull requests merged in 2025-06, with the labels that each got.

#2955 Implement `Debug` for `Task`
  runtime/src/task.rs
Labels: improvement, developer experience, addition

#3000 Hot Reloading
  Cargo.lock
  Cargo.toml
  debug/Cargo.toml
  debug/src/lib.rs
  devtools/src/lib.rs
  runtime/src/lib.rs
  src/application.rs
  src/application/timed.rs
  src/daemon.rs
  winit/src/lib.rs
  winit/src/proxy.rs
Labels: feature, developer experience, addition

#3004 Use `Limits::min` directly in `scrollable::layout`
  widget/src/scrollable.rs
Labels: improvement, widget
