Repository iced-rs/iced, pull requests merged in 2025-01, with the labels that each got.

#2688 Use "outer" positions in all window-related operations
  core/src/window/event.rs
  winit/src/program.rs
  winit/src/program/window_manager.rs
Labels: bug, shell, fix

#2585 Scrollbar disabled style status to allow custom styles for always visible, but not overflowing scrollbars.
  widget/src/scrollable.rs
Labels: feature, widget, addition

#2607 Feat: Add warning color to palette
  core/src/theme/palette.rs
  examples/color_palette/src/main.rs
  examples/styling/src/main.rs
  widget/src/button.rs
Labels: feature, styling, addition

#2627 Add `maximized` and `fullscreen` to `window::Settings`
  core/src/window/settings.rs
  winit/src/conversion.rs
Labels: feature, shell, addition

#2723 Apply `Wrapping` to `Paragraph`s
  graphics/src/text/paragraph.rs
Labels: bug, text, widget, layout, fix

#2724 Upgrade `dark-light` to v2
  Cargo.lock
  Cargo.toml
  core/src/theme.rs
Labels: improvement, shell, styling

#2716 Bump image from `0.24` to `0.25`
  Cargo.lock
  Cargo.toml
  src/window/icon.rs
Labels: improvement, widget, image

#2642 feat: add a window drag resize task
  core/src/window.rs
  core/src/window/direction.rs
  runtime/src/window.rs
  winit/src/conversion.rs
  winit/src/program.rs
Labels: feature, shell, addition

#2731 Remove a cast
  examples/the_matrix/src/main.rs
Labels: improvement, change

#2737 Update our `winit` fork with `0.30.8` fixes
  Cargo.lock
  Cargo.toml
Labels: improvement, shell, change

#2746 Add helper functions for alignment to `widget` module
  examples/bezier_tool/src/main.rs
  examples/editor/src/main.rs
  examples/geometry/src/main.rs
  examples/integration/src/controls.rs
  examples/layout/src/main.rs
  examples/multi_window/src/main.rs
  examples/pane_grid/src/main.rs
  examples/screenshot/src/main.rs
  examples/svg/src/main.rs
  examples/todos/src/main.rs
  examples/tour/src/main.rs
  widget/src/helpers.rs
Labels: feature, developer experience, widget, layout, addition

#2747 Implement `time::repeat` and simplify `Subscription::run_with`
  core/src/time.rs
  examples/arc/src/main.rs
  examples/clock/src/main.rs
  examples/game_of_life/src/main.rs
  examples/stopwatch/src/main.rs
  examples/the_matrix/src/main.rs
  examples/toast/src/main.rs
  futures/src/backend/native/tokio.rs
  futures/src/subscription.rs
  src/lib.rs
  src/time.rs
Labels: feature, addition

#2748 Vertical support for `progress_bar`
  examples/progress_bar/src/main.rs
  widget/src/progress_bar.rs
  widget/src/vertical_slider.rs
Labels: feature, widget, layout, styling, addition

#2701 always increment quad, mesh, text and image layer counts in wgpu layer rendering
  wgpu/src/lib.rs
  wgpu/src/text.rs
  wgpu/src/triangle.rs
Labels: bug, rendering, wgpu, fix

#2752 Fix `Image` not respecting `viewport` bounds
  widget/src/image.rs
Labels: bug, widget, rendering, image, fix

#2751 `pop` widget
  core/src/rectangle.rs
  widget/src/helpers.rs
  widget/src/lib.rs
  widget/src/pop.rs
Labels: feature, widget, addition

#2741 derive PartialEq and Eq for `mouse::click::Kind`
  core/src/mouse/click.rs
  widget/src/mouse_area.rs
Labels: improvement

#2755 `scale` support for `image` widget
  widget/src/image.rs
Labels: feature, widget, image, addition

#2749 Make `Color::from_rgb8` and `Color::from_rgba8` const
  .github/workflows/test.yml
  Cargo.toml
  core/src/color.rs
  core/src/theme/palette.rs
  examples/gradient/src/main.rs
  wgpu/src/lib.rs
Labels: improvement, styling, change

#2757 `Animation` API for application code
  Cargo.lock
  Cargo.toml
  core/Cargo.toml
  core/src/animation.rs
  core/src/lib.rs
  examples/changelog/Cargo.toml
  examples/download_progress/Cargo.toml
  examples/gallery/Cargo.toml
  examples/gallery/src/civitai.rs
  examples/gallery/src/main.rs
  examples/pokedex/Cargo.toml
  src/lib.rs
Labels: feature, layout, styling, addition

#2759 Introduce `LineEnding` to `editor` and fix inconsistencies
  core/src/renderer/null.rs
  core/src/text/editor.rs
  examples/editor/src/main.rs
  graphics/src/text/editor.rs
  widget/src/text_editor.rs
Labels: bug, feature, text, widget, addition, fix

#2760 Remove unused `winapi` crate from dependencies
  Cargo.lock
  Cargo.toml
  winit/Cargo.toml
Labels: improvement

#2758 Implement `Mul<Transformation>` for `mouse::Cursor` and `mouse::Click`
  core/src/mouse/click.rs
  core/src/mouse/cursor.rs
Labels: feature, addition

#2764 Enable `animation` module for Wasm target
  Cargo.toml
  core/src/lib.rs
  src/lib.rs
Labels: improvement, layout, web, styling
